api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "3143b3744e03986f1c1b5b04cadb5fb51bbc8b568c3ada27a16e825549326163"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.25.tar.gz/archive/.tar.gz"
source_sha256 = "f1b48c0237638a1de27251a3f5767ff7e0349f12fe9237ffdf45afea4734a5d3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.25-any-stack-3143b374.tgz"
version = "0.0.25"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "a0b92ef8c8a413c8de67ec4ae75a4c88e1aa5c1acacdc55e5aadd38a3c8f6029"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.5.tar.gz/archive/.tar.gz"
source_sha256 = "5f12239c3a28c5b7673ee2c4a0424a5673921ea34af68dceaecfa32ef14220ee"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.5-any-stack-a0b92ef8.tgz"
version = "0.0.5"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "67def41092a4c6ea563a550ce052e5428158c59b919a4704165890c66594260d"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.33.tar.gz/archive/.tar.gz"
source_sha256 = "1a9c455115c40d8825215ad3aaa6069e429e246c9160ff8b58e536a0fc533b93"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.33-any-stack-67def410.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "aac1e19001d285e197abd6ce88dc1959a68f7270fae9c4a552f0ebc904cd6384"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.34.tar.gz/archive/.tar.gz"
source_sha256 = "7cc28941a43d933f01bae8b2d00c89b4444d2a1a302eabdc65ca1952722947e9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.34-any-stack-aac1e190.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "15694396bc91a662842520ccba4161faba1ceed1d9f0e186698ac56c0ddf7e3a"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.27.tar.gz/archive/.tar.gz"
source_sha256 = "6dfb43399f3ba61920512d16bcc12a3ce35107d5ad62ed342e79cebef1d9de0f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.27-any-stack-15694396.tgz"
version = "0.0.27"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.25"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.5"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.33"
