api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "e241d2fe66e1b731a796ecb2e21746fe4d9c08bb35b840969c48a177eb0044f9"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "c5ac3b1ed2253bebd4dad4f93e5f383037750ab9c91e0a5a0c1e2c67c6fc7b6f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.49-any-stack-e241d2fe.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "f64da026b66e26f667b0947c5ab6ac4bdd270878abd546074457419874ca41ad"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.15.tar.gz"
source_sha256 = "9b9132bcb83af827cf5dca32c6c21cc61951da7fe6c4dceae446171b23cd3518"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.15-any-stack-f64da026.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "2d81df99d866c56eb1526d04c976cdeb15ae51e0a03c80bf9ca7310d30406815"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "da48b63e454867d1ef8fe87e0d6adc1b63049797c46d3408c8f2fbd6f7ae94a3"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.54-any-stack-2d81df99.tgz"
version = "0.0.54"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "53726f2dac478d5442bed6aa64eb80d3b292d04a018d347f4ce47d922332f9a5"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.60.tar.gz"
source_sha256 = "4002565381e93ce2fe1f905e47adb8aee284b6087b05c7b5996709c63044963c"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.60-any-stack-53726f2d.tgz"
version = "0.0.60"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "9cc50f8202e32a55929a11f33ddc0f654b6c68d64c120c1a37584ae5f1cfd69d"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "3e4537590a2c5dfd12157ea7471724bbf32a4761b306988ee366fe7ed0962a67"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.52-any-stack-9cc50f82.tgz"
version = "0.0.52"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.60"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.54"
