api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "c4ab47c86acf80a4748285fcc2d9b353ea0814a31182ac498dd1b07b31f40f98"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "feb84e8e32cbea9084ebb2eda4b768324e4f0e54dfca35d70304cbcca79222b0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.88-any-stack-c4ab47c8.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "8d79010c8b8cfa97c5e7a0e35fe8f9290a2ae8b43c90847cc7fc158c0dee51fe"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.46.tar.gz"
    source_sha256 = "c476bd4fcf5f559f720e8373eb668171e036f2459a174756f1ed64fd5a415313"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.46-any-stack-8d79010c.tgz"
    version = "0.0.46"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "b378e29cfcf0c4d57667afaf6f506c7a436b7f7011ccc393ae682be3fe05c396"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "e912f6f91b9be2254c4263c487353612e33134b4e30a505aa9010dd801b5f677"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.90-any-stack-b378e29c.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "80bd48f7b843418576c920da6f1a8a8b72304cd1c574d120a70af459a9d9cba9"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "73ea9a892b23961c6dbe176d33db8f5132926d965fabe3aceb158c4c229205f1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.97-any-stack-80bd48f7.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "b9341cb80e2de629c1d4c950cbea26b11a4bf124fa5edf66cf856132973fd847"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "8cec88b082df406164571ba759397e7ce9d5a1b03f54fea689f9a045a63fa189"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.90-any-stack-b9341cb8.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "6ee7d2773abec5cbff52c3b03551d5cf2d2f5ecc01ae7ee284fcf88407c37675"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.15.tar.gz"
    source_sha256 = "eac3a8401af38a9ff3ca71fe3ba7180dc12d233d2b135c4116a0d6ad83b91af2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.15-any-stack-6ee7d277.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "3d6886e002d41471d723d98a61da443e53ed71ad93496831973675c2bb8d12a4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.124.tar.gz"
    source_sha256 = "981572423aefa077a8bb127b6a6d3fd322d5ad1e4ea0cfaba38b61095235c8f3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.124-any-stack-3d6886e0.tgz"
    version = "0.0.124"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.124"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.15"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.88"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.90"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.46"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.90"
