api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "d2a55299b971d79656fac18ac324a0346443cfbc1ff2168c4fe8b0057c11d305"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.12.tar.gz/archive/.tar.gz"
source_sha256 = "e1ebcc6f2317a2a5183d553ec4073b3ba9b6d3f3c2fe9e4075f8f0499f620068"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.12-any-stack-d2a55299.tgz"
version = "0.0.12"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "01a8a26e609360989c6b003bfcc9343fbf840e39e9e9bdf94aae5d15c7dfa78f"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.22.tar.gz/archive/.tar.gz"
source_sha256 = "fb847cf2f43311b3de4db5712c27d94b78348216676ca102d58086ad1d1415aa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.22-any-stack-01a8a26e.tgz"
version = "0.0.22"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "02928a1a8c4adf2daa7ed5836fa81d18cf9f61f9f557026140888e1f99e28eda"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.16.tar.gz/archive/.tar.gz"
source_sha256 = "51b3606d184f0357e3e1b3446bb9eeebf6988e0f60c126de8aa52528055602c1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.16-any-stack-02928a1a.tgz"
version = "0.0.16"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "914fe466578e00da518ed20630b4a031b685b8c04f04731cd081dc154dc98ead"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.10.tar.gz/archive/.tar.gz"
source_sha256 = "abb4a256968766fc34a3aced83ca8b73f2d24949069766d1d7484f1bb8550e22"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.10-any-stack-914fe466.tgz"
version = "0.0.10"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.16"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.12"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.10"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.22"
