api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "07c5efd81e9b047061548fdb4847072a18d3dec149067967c207ce01a5e025c1"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.20.tar.gz/archive/.tar.gz"
source_sha256 = "c7494b49aa4b99ee80dcb8f67d7d594932d8dd87023ba6740b6c5a4647d683b3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.20-any-stack-07c5efd8.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "b90f8ecb73d02dc5431172ff2fb726b2b10990df13ff2acde08c4b6625f770f3"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.2.tar.gz/archive/.tar.gz"
source_sha256 = "39b5c10be0a92b508c43b5a8ccc51b9126332910248043d91ec81d61411627eb"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.2-any-stack-b90f8ecb.tgz"
version = "0.0.2"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "e4817e7d72ba4e2fd2968e882af154b5b4badf6a45aaa27420581a58c438fc1d"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.29.tar.gz/archive/.tar.gz"
source_sha256 = "8d8a5ad5641d069ae4438cf48126839334852098197b78ad0d83def2b7391bf9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.29-any-stack-e4817e7d.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "19678d1a9bac56e83a771d0fedf0f8ffc8606c8abeabd9d8284b076b746d2fd1"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.26.tar.gz/archive/.tar.gz"
source_sha256 = "0cc46c75934898d704c64ece4187a62e81c2a1be3ead64e9be92c32287205fe2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.26-any-stack-19678d1a.tgz"
version = "0.0.26"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "8b352f7478511ae99fe8fa00a31547b699764acf581ca217355d12dfcd62a766"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.22.tar.gz/archive/.tar.gz"
source_sha256 = "5a9ee543d2f6d13f00c91871d14e708f4e6c5e70f595ea664f25ed940748c160"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.22-any-stack-8b352f74.tgz"
version = "0.0.22"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.26"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.20"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.22"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.2"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.29"
