api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "c14304a5facb93212647957eb59a4e2941e0a4b35980127e3f8637800cff2224"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "f7df8325f824224c6dc96430d3878622f4da95cfddb1daf5131819791fe874b7"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.55-any-stack-c14304a5.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "bffc881f945427d2bdefdda610a9f21dbfd66b91b80e1d94bea9006c2e5f0270"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.19.tar.gz"
source_sha256 = "4b10db435b6028474882ee1d04628f6c7acd8f11eecf17416ba4649a6a90a016"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.19-any-stack-bffc881f.tgz"
version = "0.0.19"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "edab458ca31645e27d5b372ea45a3c1de4858914b3b40f8e4f4980a1c7c7ce4c"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.59.tar.gz"
source_sha256 = "8d242ba28e99b33d11ca0e1150e687da33dda16094c9f80595798f0791020086"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.59-any-stack-edab458c.tgz"
version = "0.0.59"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "a3729f707e31010832421386834ee8fd0f95afb82896f6507f2997ee8a47fc2a"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.68.tar.gz"
source_sha256 = "f0261ee79bb29fb8681c0f932b9947ad6273d780f5ff8ecb0d29787820a73c2f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.68-any-stack-a3729f70.tgz"
version = "0.0.68"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "ff9a28d6e6147fd25f3e114d199f0ae2fc10d907c47ab59a9f973a31afb87c85"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.57.tar.gz"
source_sha256 = "24c3c1b517d0fdd43dfa6556af4da5f097b13747a0311b2e097348252bc3a909"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.57-any-stack-ff9a28d6.tgz"
version = "0.0.57"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.68"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.55"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.19"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.59"
