api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "9be01df9a60f21e98a2ad52005d1bf054afa5b26d2499d559d5e67fbb22cff02"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "6d4b69d3be7619de9e454402e39a5b46580e540ade2f576fca79a20642a4d6eb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.90-any-stack-9be01df9.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "39c6a701aeb9d138a229e6d8e4a729a214a8bf1ea9ff01377ce0cea659a6b013"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.48.tar.gz"
    source_sha256 = "33f8ca51d512b5ded9796f2f70dd571abbbc66aeae2ed98f21c226bdc4fcba96"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.48-any-stack-39c6a701.tgz"
    version = "0.0.48"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "98631f288a8f6ef2fc9a2e48e4dcd3fd32f90bb88a4aa8cd03ca080656514710"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "6f892715d4d3695b720190984a55a4ae411ed4689dc3bdda28b25716cd2661f0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.91-any-stack-98631f28.tgz"
    version = "0.0.91"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "c4b7a5f7d9132302752b1fa2b5fbc0329594db41c2bf74e53f107635f300f109"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "32e644472a957bba9f2e0be92894bfdd5e25c5661d084ef7aea0e7a1facf70e1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.99-any-stack-c4b7a5f7.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "b7d4a44fce40a81a55acabbeba0646b47c1b55f7d7674802d58eb8cfc45e4b2b"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "6801e684acbf300e8edb6d486f7a7c27d8cdaff9d6e144ceafc97e3db8a6b9e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.92-any-stack-b7d4a44f.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "c65d0b6dddaf47c7e3a4173c7563c3c173e72398194a9283fcaee5d91654856b"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.17.tar.gz"
    source_sha256 = "eca6273a2bde383aa04017e0d223cab2ef2fd7ca09e5b4d99066af12ee20b99e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.17-any-stack-c65d0b6d.tgz"
    version = "0.0.17"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "cda811ab0d193b8308222f3be281932d993631635b1b91f4cc7bcdf83ae35ef4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.126.tar.gz"
    source_sha256 = "1c5cd73f6463b1e5d5c8ffa5db975194471279c5a84c014e4eb901f72e461601"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.126-any-stack-cda811ab.tgz"
    version = "0.0.126"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.126"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.17"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.99"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.90"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.92"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.48"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.91"
