api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "700c7c9088299c21b1509f8ca5c784abaf0874064f2f838aaa85bcfc24873d49"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.10.tar.gz/archive/.tar.gz"
source_sha256 = "716ec73b08bc84db171a6ff4dcd97325cbaf96a6fcff919fa59dd70d93981d44"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.10-any-stack-700c7c90.tgz"
version = "0.0.10"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "686690036c3613f567054309bef85aae4d70dd29aa8df11de6a3ea85a3a6d75f"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.20.tar.gz/archive/.tar.gz"
source_sha256 = "4d10bb3296f3802d2fc22bdd6deba5b856f6d375cccb3201d45ca6741c1e7ed2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.20-any-stack-68669003.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "d7eada3779ad1b21a8f86b9b8f565e9cf518f06750bfdd5d1b59d88832ebaff0"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.15.tar.gz/archive/.tar.gz"
source_sha256 = "a095d142d5ee52778b18c3575a27a282d665c2176eb4fef89f84634a4e37cef5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.15-any-stack-d7eada37.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "2a8f9b8440786065628cac9bae62c31c27069831271ec4a4431cfe4116ac8bf7"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.8.tar.gz/archive/.tar.gz"
source_sha256 = "87b908b7d92edac3af878dcd297a12ff7f7b9e8a2364cf999e82616509fa4bbd"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.8-any-stack-2a8f9b84.tgz"
version = "0.0.8"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.10"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.8"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.20"
