api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "aaf1da5b995b73262eaca1abfc15ccf8e37fdb589858dcc782b412e896016c0a"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "be3fc2e4f82cfc98ceacf19b384ca1fd88c4d06dc260b47233a3f042f32179f8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.107-any-stack-aaf1da5b.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "44819580bdb583e01f02aeb6964df5caad4f91acaf8da6ccf195b305db508553"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "30530eeafe1349b32b0860fdc18c4bc7fd51f5150fc62f8c9265f3801aec13e5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.61-any-stack-44819580.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "ff3a4019c91947b8ee85d5da457d4c43d60a511d536fcedaf7570acbe4a63494"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "08c3f68b3c38e04731e5ecf364fce002a96e88cd46e1f073a2f32d5879721241"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.107-any-stack-ff3a4019.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "ec1f18073a1fb7c45745ae52a5393bdb24713c5fb1be822ceec326c2c4b682b3"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.118.tar.gz"
    source_sha256 = "c4d552c3b1879a5632b54037e51996f3a0852692b31bae7066b73a8b0dae9753"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.118-any-stack-ec1f1807.tgz"
    version = "0.0.118"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "ad4e4e25376b88b1953299055ed74c8f906b162d3cb4978e411ec8ca36a876dd"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.113.tar.gz"
    source_sha256 = "7050fc5ab49e15f811ca44c9df390d68fbd058a8da0fd97768e1cd60357078d2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.113-any-stack-ad4e4e25.tgz"
    version = "0.0.113"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "b29061c02dbd5d519b753fa5070676b44e241d71aa92dfd03bc03c24f7e14a74"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.36.tar.gz"
    source_sha256 = "5e5f377f40e6c3b4605c86e165a24be2b7afc882213b8f43b5a2c560e9aa027d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.36-any-stack-b29061c0.tgz"
    version = "0.0.36"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.36"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.118"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.107"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.113"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.61"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.107"
