api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f80bb5acf5663c758e66d928c3ff11c5f6fc1e5edb991658a9a000bb91af3158"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.34.tar.gz/archive/.tar.gz"
source_sha256 = "d8bc24680ee5838104c44961cbc15f78d24310f869309c7af5b7dc3c186a05e2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.34-any-stack-f80bb5ac.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz/archive/.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "55630157e143e1e6b8863f9f20dd54488b835c27e57c0a2a99fb14602e3fc4c6"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.38.tar.gz/archive/.tar.gz"
source_sha256 = "e76e1f9aa3fd2a2f6ffec585f4134b6cf5d9749e520f4a39982679c69cbd49e8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.38-any-stack-55630157.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "bc9d283482c06e4470ecbaeca4cb4aceb0cea4079092844622580cec5793df1f"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.42.tar.gz/archive/.tar.gz"
source_sha256 = "0df1e3d6d2b1b1428a867d9d2eb760ad23364e9919fa7818454d89799e57dc35"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.42-any-stack-bc9d2834.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "24fa010229424ce7d3c006845b44cf7975a8871a5a7e432e8b461f8158ea3b7e"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.33.tar.gz/archive/.tar.gz"
source_sha256 = "385797a89037590f4d34c824b28856b6495d5534f3accebc0b3d33d3908dec3f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.33-any-stack-24fa0102.tgz"
version = "0.0.33"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.38"
