api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "e3a66c1847f3de0eb0f8e0d7ed8d5a53925498d7f8d3bbce0492a13fc121990c"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "c7a24a465b1ae9ae8b5623f690084c295013fd9672c1dc8314b7d8f0bfd37550"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.94-any-stack-e3a66c18.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2e8103058ed32164d7b46cbd24e174cc5d2a53818cf7d4a58ae1a3d833c237d2"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "a4220357532394154ed004a649d4372c4df50a92d9b54b0c99b6fef3a1d68993"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.53-any-stack-2e810305.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "f55ed98e62651c3b8f2a59916f4d60c525136dc19596d11b4a0aff75f6040707"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "eb52134b340baf06e20d301cc65b190cabc40da01d6607ff6efa723361cbbd62"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.97-any-stack-f55ed98e.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "c96154563dc4de398bbc5e04d63d25c68a07da1a155b2725eb3a3b8c8638da70"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "edf18b69aa1ed78eb7f9fc2a506adc9a7213b34e19187bb3299992b6fc1d059d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.104-any-stack-c9615456.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "d6d14581348877b4eadf2caf71e451f2f28b68238d5e871bfae02b21fa473956"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "4e22cf812bc38fd69fe8a23ef77b2fa082571ffbfe1ee7ba67efa6824cf4a667"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.97-any-stack-d6d14581.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "0c3e076f41d1d6e8a92b9f6897cf1b76cc224d75ab41827d9222533301795b70"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.23.tar.gz"
    source_sha256 = "ef6704c8126a053bc28440cb047ff5209ec9f0d48f8785f1aa2f618646f15809"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.23-any-stack-0c3e076f.tgz"
    version = "0.0.23"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "00e0e332828ca0f780fe62a3f29bd4e8854672135d55bf06075df97706bf0a73"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.131.tar.gz"
    source_sha256 = "b6150bcb6213b85a8d89491f5d516db568ca6afa21a2506116f77f9cf0780b75"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.131-any-stack-00e0e332.tgz"
    version = "0.0.131"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.131"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.23"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.104"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.94"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.53"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.97"
