api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "bb9989ecc8dcb56200aeacbb95fa681f75dbe3c9b5e73b71f1ddf215e9734cb0"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "7ddbb926032b4b73af8067af16fe8d9a5b92f47cbf53769be393a553453b1503"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.74-any-stack-bb9989ec.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "fdf5b23a52dfc9017f586ee4a79d8534809841ab4e0c10021299a207c27e94ee"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.38.tar.gz"
    source_sha256 = "0af21df39d38b4a695f12c18dd0de8f8b6176016af32531645c1425902dbbdc3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.38-any-stack-fdf5b23a.tgz"
    version = "0.0.38"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "52f1c2b6b8fec57a3ff63d25e4cb01cefce80eaae7d7aca702e0b646dd8840b0"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "d10280b7e4046ef16848d9101781a55635572b70593cd061958ebdc14dfbb229"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.80-any-stack-52f1c2b6.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8b714b7c5386e10160e8b76b73e8cd572c5f75f99f48f4e642556dda1ca1dff7"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "67c6d8db71998c5da8c771516f5355f7d104665c0cc3c3c326d0280009885403"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.83-any-stack-8b714b7c.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "5bb59fe8e1a3b27633b581e8e1a40c95665d1a46d1bda2a369837ce9d1a9e0b6"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "da0c97d991c9c974d3689eb4d696db76c2a9167ee06546cdf7ea9d2e02178615"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.72-any-stack-5bb59fe8.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "a313800accf3a9ac271e77d43882b7f73defdc200fdfc327fd99e428b8a45c91"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.6.tar.gz"
    source_sha256 = "78291fd001552420efae73ff6691e67ccff2bcc7bcf0208e01fbac83f29108e3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.6-any-stack-a313800a.tgz"
    version = "0.0.6"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.6"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.83"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.74"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.72"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.38"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.80"
