api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f3246445de1acb583b4ba037db208d67eed403a78cc44c18b836896c315f64a8"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.15.tar.gz/archive/.tar.gz"
source_sha256 = "14098480d4b1e5079b6d945e3155f1243396a70929e4e1ae311bbe6228086f4e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.15-any-stack-f3246445.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "a4fc27c4cca9b0d84864714e6dd8d18af405af4a50f5785cc905f2ed26d18850"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.27.tar.gz/archive/.tar.gz"
source_sha256 = "232f86e4f2fedc9460801310b32d23c6aa746e19a1d1a62b852383e535bf1824"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.27-any-stack-a4fc27c4.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "ac234d7ef70349c9481c04347e4e7a840727dd948a978205bee7627f01f53b77"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.24.tar.gz/archive/.tar.gz"
source_sha256 = "c54b65ac8731f72ba415e6c56da9b5ecf879d419790e85afa18e40392e582b95"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.24-any-stack-ac234d7e.tgz"
version = "0.0.24"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "5d2e3b268787005df714fa0817685d1f06667048cbcf00726d5e4c54e0911213"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.16.tar.gz/archive/.tar.gz"
source_sha256 = "d0cb38c0f02acc7dbb36e1f2ca0f0d801e26f54b497dd26a021b4ccfa38d6a72"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.16-any-stack-5d2e3b26.tgz"
version = "0.0.16"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.24"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.16"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.27"
