api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "1899534654f48ac86f336929266975896c06a1ce9febdd1cfe9818662b369e81"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "5652f71c37884c77d8c025f77fac0b0427cb4cd17643b5c0fd83cb369a038b99"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.104-any-stack-18995346.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2525bb7a9bc27af976e45ab387ed899b2f3a749168cc4e25d913b8a10cc4ed05"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "abcf8870d10846624c3d87cdf0958a2257d476fe29c17889f0d876bbfb5a7cb9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.57-any-stack-2525bb7a.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "babfedcec5b6aafb989911e866f1ead1eb95e84bc8052455c710f091d5732c6f"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "21adba9ed660c4e6a44a4f27c1907908d6a9ba01115fbcf0a311fd7a8fa1a5bd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.102-any-stack-babfedce.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "bf767f7f57879c63c31fb240b41709cbc913f033dde9c91a06cf2785934da2f2"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.114.tar.gz"
    source_sha256 = "3c26e552e4a7d932615cd2495179207bcfc54679b1319e2273b5cfb261ab05ed"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.114-any-stack-bf767f7f.tgz"
    version = "0.0.114"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "6b91be3c86a97e6c4b9cec13060d74ac49367e7cea2c5fc3a6f210021ab9f779"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "ea721d770e6dd7968b26c02c935771b3425d4d2e3b1586a93de08fdc5a0ea0a8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.108-any-stack-6b91be3c.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "998e7d0626f6f45f2c27436a030a7cded9a9c45d0ec23015175615427a3c37d1"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.30.tar.gz"
    source_sha256 = "62db5a7be26c9eda8b767817cdbf4fb9ff2c2d799e89bfe804e5d7069bed58fc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.30-any-stack-998e7d06.tgz"
    version = "0.0.30"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "b3861b6f7d1c851d029262637801689f81ab0e09de06a0c3903ce60104528a8c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.144.tar.gz"
    source_sha256 = "60a8409f3a00586cd6a747140735977628ceb1e32ed14ce25b4205ce476ad9ec"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.144-any-stack-b3861b6f.tgz"
    version = "0.0.144"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.144"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.30"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.114"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.104"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.108"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.102"
