api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "102b89380cf0c863b3f59983915cbb15bcec33d4b955cb6e994fc455fda37506"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.32.tar.gz/archive/.tar.gz"
source_sha256 = "b4ce06cf92fd38a918e3a2816aa29481e5b67cf1c7e3d4166ae9dbc1bd19f077"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.32-any-stack-102b8938.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz/archive/.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "d286031655af09ce7e16f05bdc3d07a3287c88ba4b331625897f52bd963fc24c"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.36.tar.gz/archive/.tar.gz"
source_sha256 = "9f6c91c9450877b929d2f874d1f6beac68f5c4e5161ade5e16d028e0c59dfc88"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.36-any-stack-d2860316.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "5634bf93bfa8e18e936605bff02dd06b77334b63bf194f8dd19c3476f6de4639"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.39.tar.gz/archive/.tar.gz"
source_sha256 = "9ff627d89c4e264747ea94ac49e235de360abb0a2b714ec081947a153436aa50"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.39-any-stack-5634bf93.tgz"
version = "0.0.39"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "58f3708d392bd0b5c83069a2a2659bd161e75e02b4256b16f576e30e7e66020e"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.31.tar.gz/archive/.tar.gz"
source_sha256 = "0b42aafebb164470513a3151e6f2d67135f11777116dcadd0d37b57ed3944d14"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.31-any-stack-58f3708d.tgz"
version = "0.0.31"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.39"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.32"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.31"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.36"
