api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "9c4f704d9b9b9bf916b49d931cbbb5a04e6fbe374f6b4d749289b83e0444969d"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "dd853c31e41e6fb240ab5698399a3c6dfcdb4486b04f2e75ec4b0cff14bf1bc7"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.45-any-stack-9c4f704d.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "0ad0af866a38eff1dfc4e8dfc18e9855f406ac2b14b4e3d010c63b33b0f28cb7"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.10.tar.gz"
source_sha256 = "22fbad9c03d12f4a9dba1c2d52d5cb1dd9c4d99f000a18a25c6033a33bda6433"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.10-any-stack-0ad0af86.tgz"
version = "0.0.10"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "6d433e12b57311843fda6b4d33e4e4d1a45fe030d5ad9050b1df8ba733adf15d"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "93d13792c585be092d61044244e0977d810824ac566d4cf3b1bdcd47e18ae4d6"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.49-any-stack-6d433e12.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "73b55c76b7a330a8f9db6b0c85b63adccd29026269fb560d06a77dc05c25a67f"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.57.tar.gz"
source_sha256 = "6fe3e6ac1c01686f06b64bf0617e1e2d12e3421e96116244502bb368bac77c72"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.57-any-stack-73b55c76.tgz"
version = "0.0.57"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "9c2921ca5c15fd6364389b273e4e2fe82f20a525ac2333cb6ed1f2742384828a"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "c212930c0191389e11c96c09cae69421479aa46033f9cdf8dcf1761e6f61cb11"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.48-any-stack-9c2921ca.tgz"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.45"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.10"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.49"
