api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a7b3c594db8187168b76c73dca853c99b0ba9fddd1efc8a3f8fb76d38a85c9e1"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "aaba9353969f4be9a5b641107c36d7e6dc8e4673bc7fe551ea72b72c7f1b3555"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.93-any-stack-a7b3c594.tgz"
    version = "0.0.93"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "8167324aad586fbe4201e87a6ae8193b586557a48f2fd2713f1750c522302aa2"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "b51fe1b5b0e8f512a6e29451850530313afb741b79ce934d4991572fd2851c0d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.51-any-stack-8167324a.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "6c0a8280ec9c7b200d8e9df9c388cdcf8286ef011fee0fb829636fed1d657ee7"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "4504d61b1312eeeed56fb00400a1526a0db1b409c276593118bee0d36591433d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.94-any-stack-6c0a8280.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8110a60401ffb7d115de88e028c5a764ef939cf4b365dc4251362ac2ef9b51ab"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "e59f423b4b51ef1eef6baddf4998f62eb06f06e152d4a928636e98d422c19a09"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.102-any-stack-8110a604.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "011f78a94dd34c253000085ffbcbf295c08edce56229d436da4c9cfe0e7781a3"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "86a719c14caa161405258b40ad34de3cebb031c49c809b6e1e4c471b1d40c314"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.95-any-stack-011f78a9.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "324976e96bff7373e9badf39919ba23df1454378b3575d76f88ca8afe0a4392c"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.21.tar.gz"
    source_sha256 = "f4282484c8c7efab7a43b7a7dc1ef8374566cfeae5e07fe910450b938d7da0af"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.21-any-stack-324976e9.tgz"
    version = "0.0.21"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "d7efe6bd590c5da7789eb1b2595501677a7bffb274897a84254d8d508493c424"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.129.tar.gz"
    source_sha256 = "0eaa5df14a3439065b205ec9b6b891314247fbe79c953ddd87425e7d81e9443f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.129-any-stack-d7efe6bd.tgz"
    version = "0.0.129"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.129"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.21"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.102"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.93"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.95"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.94"
