api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "e240dd0778c6c09c91dd369a868a6bfee3111b914aefdb1f4d2b5e44982817bc"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.58.tar.gz"
source_sha256 = "422037e3c10f289c0007e527324ad331b6de309907328beb4cc77e8a5e1f7381"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.58-any-stack-e240dd07.tgz"
version = "0.0.58"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "21e0b70847f91b81869cd28066fec9e0cbdba15fd3b4635a96bc50c8629a240d"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.22.tar.gz"
source_sha256 = "63db76ed6add97350623bbbcb664e262c444dd8eb934d724a30a2ac84045fa66"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.22-any-stack-21e0b708.tgz"
version = "0.0.22"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "d186de6d4a2eb0a2806c4b34de62b955d10b0a4f2ce2988ae1da0fb10e857b8d"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.62.tar.gz"
source_sha256 = "acd4408a2c40956f747c5043b6a9c6cfd00331276d61b5908c24252bfabea0f6"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.62-any-stack-d186de6d.tgz"
version = "0.0.62"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "6cb45b14cc92213b548196656114da16599a39a1f1eb28747884508a95e6ea8f"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.71.tar.gz"
source_sha256 = "6be6ea364e4bfbecd827a92973c62b32602aebb7eeaff1128dab02d2d1d41403"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.71-any-stack-6cb45b14.tgz"
version = "0.0.71"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "2df184532f329d991c12eceffaa4fbb4c714e7aab7477a3cb770a5f01dc215ad"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.60.tar.gz"
source_sha256 = "00711c260b8b5ebbed7034531d9fba135be332f6a8a41886f26e8a10f6c090d9"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.60-any-stack-2df18453.tgz"
version = "0.0.60"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.71"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.60"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.22"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.62"
