api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "1de4759ecbe076257e178312b4c4c44c74f4d3ee0d4e5ba705d09e484eeb29a1"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "70de697df06ed6b45563af60feb978ffe0bc1c5b07943d73f3c7eb31698f3a9a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.76-any-stack-1de4759e.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "fdf5b23a52dfc9017f586ee4a79d8534809841ab4e0c10021299a207c27e94ee"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.38.tar.gz"
    source_sha256 = "0af21df39d38b4a695f12c18dd0de8f8b6176016af32531645c1425902dbbdc3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.38-any-stack-fdf5b23a.tgz"
    version = "0.0.38"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "268b08d59b9a13c19964256d70a2cdcb4cfe7a970f3302c75e9fac71ce099f04"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "59a5c5d38fdbde1b404adea5c04b905a69830097ed3a3933bd3be37c603aee1d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.82-any-stack-268b08d5.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "1b4d2806ac1ed48dd820f37aed24fcea068c21953c42c7800e11c7ea1103d68a"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "cadf1bdd832831881420faaea3cb8267e2e2eeade9a92089fff08a72749936ff"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.86-any-stack-1b4d2806.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "2c0cc2076348e564ac673dafb07748ca6f6e41bdccdd0adb64f0144595d897eb"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "6dfc2b2c5bb453e642d7248a045586fcff714279b880ff7c41bf6eac7eab2023"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.75-any-stack-2c0cc207.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "963b6d98ead85f5e32fb3b66f74143cc106db6a5ec238eddf53e6ec8a1f69279"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.9.tar.gz"
    source_sha256 = "bee58760d864d63e3387e6675607e0196b044937107d3f578f09aa059d5be695"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.9-any-stack-963b6d98.tgz"
    version = "0.0.9"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.86"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.76"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.75"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.38"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.82"
