api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "bb9989ecc8dcb56200aeacbb95fa681f75dbe3c9b5e73b71f1ddf215e9734cb0"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "7ddbb926032b4b73af8067af16fe8d9a5b92f47cbf53769be393a553453b1503"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.74-any-stack-bb9989ec.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "fdf5b23a52dfc9017f586ee4a79d8534809841ab4e0c10021299a207c27e94ee"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.38.tar.gz"
    source_sha256 = "0af21df39d38b4a695f12c18dd0de8f8b6176016af32531645c1425902dbbdc3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.38-any-stack-fdf5b23a.tgz"
    version = "0.0.38"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "2f7e31a45b0fd76eac6fcfc6db74527aba59804071bed162aad330f41a5b6742"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "a5b2af5099ccb0590090b8c8d4b33d9c2da218bc7c938d61fccde3649fe616f6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.81-any-stack-2f7e31a4.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8b714b7c5386e10160e8b76b73e8cd572c5f75f99f48f4e642556dda1ca1dff7"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "67c6d8db71998c5da8c771516f5355f7d104665c0cc3c3c326d0280009885403"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.83-any-stack-8b714b7c.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "0fe716f9b957398f060bdacf3e71a46959fcbe1ffe3ac7727ec15cb7740e682e"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "13abd20ec09e48b049fd2d07172826e5e7e8ebab1bf8abae9f76476208b63e79"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.73-any-stack-0fe716f9.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "45a7d616deaaf454dbb82934d218cc36a0b71ad3b2a9cf18aa26c66bdd43a305"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.8.tar.gz"
    source_sha256 = "1936b715a1039450889ab7816330b6ebb8cdb89db9a94640761d68b27054eed0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.8-any-stack-45a7d616.tgz"
    version = "0.0.8"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.8"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.83"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.74"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.73"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.38"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.81"
