api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "24fcac4566b3ee6ce0e48d67a3a2f2dfce33b24c9a4e9e113be5a4e576502881"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.36.tar.gz"
source_sha256 = "312551a9025e0d80caac428c191f09e1ba55ac790dcf06113ee9dc85f0e99019"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.36-any-stack-24fcac45.tgz"
version = "0.0.36"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "95165f867a5c34c8c2d6a0d2dfc659e0e172498201ae27de36ecf54033ecc73a"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "461bb77a5d550d38fe667cc329347f9c034b2b75b708e276617fb8513ec62027"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.41-any-stack-95165f86.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "583db6649acfd053b3523db8f4c87c44436e0a37fbbd985a4760dc36c914f0e0"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "3ca02188372cbb163ff1d977263547294f54560b5cc9b3d9b10ed7c315dff96f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.49-any-stack-583db664.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "2027ac2b7c66b15b1e8eb9df467745c19318fb919affb13a7d33f10f0d8ac4fc"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "fbffa70ed8766ea0ebdfd5bd94491d523d54c92f359b877e4d312fd760731d68"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.40-any-stack-2027ac2b.tgz"
version = "0.0.40"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.36"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.41"
