api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "ff4965eae1ca007eb8f1934e5dc10bcdc5d32e8bf1b97a5498f3bf5f06fb6096"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.46.tar.gz"
source_sha256 = "fe12b3202a4f8a75976cb134b29195d8ef580625cdc2d2bebeeb51069acdfa09"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.46-any-stack-ff4965ea.tgz"
version = "0.0.46"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "0ad0af866a38eff1dfc4e8dfc18e9855f406ac2b14b4e3d010c63b33b0f28cb7"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.10.tar.gz"
source_sha256 = "22fbad9c03d12f4a9dba1c2d52d5cb1dd9c4d99f000a18a25c6033a33bda6433"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.10-any-stack-0ad0af86.tgz"
version = "0.0.10"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "6d433e12b57311843fda6b4d33e4e4d1a45fe030d5ad9050b1df8ba733adf15d"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "93d13792c585be092d61044244e0977d810824ac566d4cf3b1bdcd47e18ae4d6"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.49-any-stack-6d433e12.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "d0549d49c75134ff399773f29a4b2eef5850109ba5b5069ce6e33918dc73b0a7"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.58.tar.gz"
source_sha256 = "7e22b5acd723a0854ab62f6e9050f81bc50358759d7dd9545e450f10785891db"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.58-any-stack-d0549d49.tgz"
version = "0.0.58"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "9c2921ca5c15fd6364389b273e4e2fe82f20a525ac2333cb6ed1f2742384828a"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "c212930c0191389e11c96c09cae69421479aa46033f9cdf8dcf1761e6f61cb11"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.48-any-stack-9c2921ca.tgz"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.46"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.10"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.49"
