api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f567fcab7398a5a403fd8678b933094bf52c2328190ef526954b166a29cc0fb5"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.11.tar.gz/archive/.tar.gz"
source_sha256 = "ae1eebf53849180e331737fb3b022e0756e9ed5717bdea6a95b1919239d0c6fa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.11-any-stack-f567fcab.tgz"
version = "0.0.11"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "686690036c3613f567054309bef85aae4d70dd29aa8df11de6a3ea85a3a6d75f"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.20.tar.gz/archive/.tar.gz"
source_sha256 = "4d10bb3296f3802d2fc22bdd6deba5b856f6d375cccb3201d45ca6741c1e7ed2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.20-any-stack-68669003.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "02928a1a8c4adf2daa7ed5836fa81d18cf9f61f9f557026140888e1f99e28eda"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.16.tar.gz/archive/.tar.gz"
source_sha256 = "51b3606d184f0357e3e1b3446bb9eeebf6988e0f60c126de8aa52528055602c1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.16-any-stack-02928a1a.tgz"
version = "0.0.16"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "5bc2352a9106b620ddd89f9670c18470820923a68a723cd62ddbd716cbd66fe9"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.9.tar.gz/archive/.tar.gz"
source_sha256 = "dda63021c8b25ef4ccf8daad2d471c8adcac2063ca22bf3baa32f4bcc503ddd5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.9-any-stack-5bc2352a.tgz"
version = "0.0.9"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.16"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.11"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.9"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.20"
