api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "bf12d2168dc445045737b7ae10ff6ded8fd849fd9d72839af6e4a3669b91755e"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.112.tar.gz"
    source_sha256 = "a743daf90e477a2a7f730406893faa66876cd880095afafd04203b8588daa42d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.112-any-stack-bf12d216.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "7b871ab13c13a9e9f00ecaf4862ddbd0adca25ba0e89c4652abc11bd966aafaf"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "343465e4d4204a9a48f1822c38e27cade7668a8b7621c186febe7b9df19c03ab"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.65-any-stack-7b871ab1.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "4c4c151ae6f3d385a9372acad2777ae0d200ea907ae105c7980d4c7cd77da0af"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.112.tar.gz"
    source_sha256 = "6b663ee0982b68280d9098a77ef206ee8b4699a44cdc89e6c6821a9f11728f37"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.112-any-stack-4c4c151a.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "dced95872e663c1bea98f51e9bd65dce5bcc7d5cdb13e1a96ea36e7b9a749fd6"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.123.tar.gz"
    source_sha256 = "47648cc72767a5b7fd8c27476b40f72cd3cabf5ca47dd565f26a292d62e42e53"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.123-any-stack-dced9587.tgz"
    version = "0.0.123"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "b4ff70969819de535caee048d3fd6dbaf51b3f37fcb0a0f2d0c83f5ea39b081c"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.118.tar.gz"
    source_sha256 = "9c06b1f1b5def22702bc5c539d7dce88ddf001c1c9cfafc5b8ef9c3c1bfd2e6c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.118-any-stack-b4ff7096.tgz"
    version = "0.0.118"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "b11787055bb5112210bfed5f3a0a27a5cfcbf8b36c8a38da16e90e05c8c4c560"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.40.tar.gz"
    source_sha256 = "afa517fe4614c2c4e6fafd081d22da04476ddadef71b59477131436b538735b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.40-any-stack-b1178705.tgz"
    version = "0.0.40"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "85e93f4e818ddb0dfc6e4bcf5130291dd6b74c9c4394fc124dda1e9e9851f79f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.153.tar.gz"
    source_sha256 = "1907503b7d82aff117f9d6fd5f1c42e531337b157093a5525519df1af9f5a5ae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.153-any-stack-85e93f4e.tgz"
    version = "0.0.153"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.153"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.40"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.123"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.112"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.118"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.65"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.112"
