api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "c08a5618dcca044cffe14e2ca07a5ab495f7f0faddbf07601db9f194429e38b4"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.127.tar.gz"
    source_sha256 = "c0068ccb62d786d06c350d363cb71a75eba366e923891a09718651b63faa4027"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet_0.0.127_linux_noarch_any-stack_c08a5618.tgz"
    version = "0.0.127"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "4349ccd18bf38a63cc447d47ccb326234afb645cf122d276fbcccbc21c00b07a"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "87b4f9c1d8bfd723b434a05dcb6cc538d542171e964a02403ad8feb419adee97"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.68-any-stack-4349ccd1.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "0ec017ae0096fedd637605e3b637c4c9492872e9e8928fa7f4d782239e044872"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.120.tar.gz"
    source_sha256 = "7a487b95a586914001e19c548f5992b214f8014eb1a0bf239c5abe930be5c18d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf_0.0.120_linux_noarch_any-stack_0ec017ae.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "495a474d37bc44a23a2e642bb8fb5f0baef56c735a08356beec1475fba123c0c"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.133.tar.gz"
    source_sha256 = "e5161146f310e46d1e37baaefbc47a4b1139e0e139f5704ed3534f8ec3116d79"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime_0.0.133_linux_noarch_any-stack_495a474d.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "94c8f3074e13a2bf4c28d1add8d7cc650d9253c62527384f665d92f1c41380b8"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.131.tar.gz"
    source_sha256 = "92b09e5858b51080a2df82723bb1444c95933b27778c7b3274078e585524dbf0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk_0.0.131_linux_noarch_any-stack_94c8f307.tgz"
    version = "0.0.131"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "d709b49ebf0ab416779eb7d1c2a576139ddc83cbcc95d56a708ad2416885406f"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "4c2923c72063a12f044f6c3951b850689aa2c8836f8608538f918c64e38fbfb4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu_0.0.50_linux_noarch_any-stack_d709b49e.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "7a4319d9afd68c25b4d213a7fe0e5118eea6fa735939c62029acc6ed16f24e21"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.176.tar.gz"
    source_sha256 = "be910ca63de2892d3da432b58031e339c3e6d263d4ef8bfc988d4a4fda95a043"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.176_linux_noarch_any-stack_7a4319d9.tgz"
    version = "0.0.176"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.176"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.50"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.133"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.127"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.131"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.68"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.120"
