api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "173ae8d89ec5cff4acc59329eaa114fa1b939010c15d6f2189fe547064632c94"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.23.tar.gz/archive/.tar.gz"
source_sha256 = "49b31f10daa539f7cab255b40fb597fd475f71691cca74650b2f736fe2d837b3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.23-any-stack-173ae8d8.tgz"
version = "0.0.23"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "31013590eb9f297ceef1d761326021fba5bcbf3dfcfb7c2abf089bceb5862d43"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.3.tar.gz/archive/.tar.gz"
source_sha256 = "53f4849141a58f2beb119beeaa91291eca3d20e26fc7bac75740b4ade035d0e4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.3-any-stack-31013590.tgz"
version = "0.0.3"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "67def41092a4c6ea563a550ce052e5428158c59b919a4704165890c66594260d"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.33.tar.gz/archive/.tar.gz"
source_sha256 = "1a9c455115c40d8825215ad3aaa6069e429e246c9160ff8b58e536a0fc533b93"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.33-any-stack-67def410.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "288aad6e90f619dc202eef60639b934163a6ae9b23943d88308e984eeadadb11"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.32.tar.gz/archive/.tar.gz"
source_sha256 = "3ceea236b89cd696d862789176a2c6aff3cbe66c9511b307bb9bc7731b52d4e9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.32-any-stack-288aad6e.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "15694396bc91a662842520ccba4161faba1ceed1d9f0e186698ac56c0ddf7e3a"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.27.tar.gz/archive/.tar.gz"
source_sha256 = "6dfb43399f3ba61920512d16bcc12a3ce35107d5ad62ed342e79cebef1d9de0f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.27-any-stack-15694396.tgz"
version = "0.0.27"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.32"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.3"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.33"
