api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "f788ae888162156b1caa14e76e39ded322d507ad725a2cae65144d430bdec18c"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "232f067fe636955b9fbfd282cd1647a4e93075a777d267c7b25822119351a87d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.79-any-stack-f788ae88.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "b492fa4cdcae5ca1e0a4a13f34cc6a1a0fef791e9b3fc6be78c7df6d74bd91bf"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.41.tar.gz"
    source_sha256 = "26f673905606ae6f7d19e6b1f2e7aff93a61bd4e585a864398fe20c8fc7bca73"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.41-any-stack-b492fa4c.tgz"
    version = "0.0.41"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "d9fa56354af3246af6185a09c79536522b39187e3252c4c1c85d21f0b069fe13"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "7ee092e9a4bc97dbbbbff069da41551589b6eb50cc5b3d0f7a87a8f6b71629e0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.83-any-stack-d9fa5635.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "1d0538c1f1d8f18e9e62e67a0d2fbead9b4aff3b447e5189cfe2ec16760d05fc"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "5bb3be23e0a5a1ccf3004364143c0611a2934cac9f27bc665999f3384f3ea256"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.88-any-stack-1d0538c1.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "2398ff230b3f6839814fd56887f1de50ba0c2548c2f4366223ab47dd164f1edc"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "9c4f06264c331e5e2cac42f64d48e48da4fe93235cc8ff41d25b0be69e831ad1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.77-any-stack-2398ff23.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "963b6d98ead85f5e32fb3b66f74143cc106db6a5ec238eddf53e6ec8a1f69279"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.9.tar.gz"
    source_sha256 = "bee58760d864d63e3387e6675607e0196b044937107d3f578f09aa059d5be695"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.9-any-stack-963b6d98.tgz"
    version = "0.0.9"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.88"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.79"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.77"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.41"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.83"
