api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "9ead8e568789ad50bb64889b6c880375eaab469c63c081da97896423cd0dedcf"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "0bf6878cc5229c71dc9867d1ee61db5be961e8826555c87c2224631b16b618a4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.84-any-stack-9ead8e56.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "9a7b6a1b165736fae3676346e96e443570467bf3c7a40d2191e61abd96d16780"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.43.tar.gz"
    source_sha256 = "d0f2ba5f9e6e05c4115ed6b4fa87ed323b88477d932bbdfc8f9a36de8da51ce7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.43-any-stack-9a7b6a1b.tgz"
    version = "0.0.43"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "f0ca71a290724fd968d72cf71db9261a5c54d695a00b3eb73efebbbc566d3ba4"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "9b2c5ff871ceef8bfa4535babee44f470aa66463af994210bd1781f920b90645"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.86-any-stack-f0ca71a2.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "b53e59f1477b3acff5d2a824747980574707b9c8bf195219c1d823e85d4d88ab"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "459818a93b72b6c36c1ca36c4058eae26d46996ec2db2c8e87784ca1518cfda6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.94-any-stack-b53e59f1.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "12bb27e88d8d527fc62b7c711d08023516ca8b678d125c7ca2ae09fb9c1f3963"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "6bb735b87b6237a9e7fa4100c3492b0e8344126eff3921a79a1b546a20f53c49"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.85-any-stack-12bb27e8.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "0ae2f426be6bc185e0aedff22643eac763aa2f5b970897d3d40a11b1a40e3cc7"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.11.tar.gz"
    source_sha256 = "da7b6c6d9fbbb4489d6abf51febe466a1347012524db0503bb564cd26003b2b6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.11-any-stack-0ae2f426.tgz"
    version = "0.0.11"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.11"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.94"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.85"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.43"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.86"
