api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "986021b947a068ae5e2d4993f26469ff1cbbdd009a0c5286844b9137be500a2e"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.27.tar.gz/archive/.tar.gz"
source_sha256 = "666bc572fc6a9611af0c42ac1d717657931596bc0f07defcc2b32b0710310423"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.27-any-stack-986021b9.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "a0b92ef8c8a413c8de67ec4ae75a4c88e1aa5c1acacdc55e5aadd38a3c8f6029"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.5.tar.gz/archive/.tar.gz"
source_sha256 = "5f12239c3a28c5b7673ee2c4a0424a5673921ea34af68dceaecfa32ef14220ee"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.5-any-stack-a0b92ef8.tgz"
version = "0.0.5"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "60b98fd5b818b49bafe1b5d334b1615683ec22a565d65aeaf1a66bc5fda420de"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.34.tar.gz/archive/.tar.gz"
source_sha256 = "e6dd37979608902205adee9f4a62cbe42c5b6b7c19a0fc4f25851fb752b26f2f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.34-any-stack-60b98fd5.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "e93ed6edd86c5d2bb6af678fc7abc4bb1f12bc2a2c3edb64d1a875dff0a4b873"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.35.tar.gz/archive/.tar.gz"
source_sha256 = "e006e90796a378535106d2e97d49181c96dffa48bfdd9844725b02d0cf85698f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.35-any-stack-e93ed6ed.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "15694396bc91a662842520ccba4161faba1ceed1d9f0e186698ac56c0ddf7e3a"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.27.tar.gz/archive/.tar.gz"
source_sha256 = "6dfb43399f3ba61920512d16bcc12a3ce35107d5ad62ed342e79cebef1d9de0f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.27-any-stack-15694396.tgz"
version = "0.0.27"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.35"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.27"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.5"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.34"
