api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "69664e995b867906dfd3f897b878e196fe39a7c4762e0f2b8505dc311fa75ca8"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.40.tar.gz"
source_sha256 = "bec3a16df961d1d63359ee41414fb4835c71119e44653811a017e10d27e5281e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.40-any-stack-69664e99.tgz"
version = "0.0.40"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "060f349c17b09b56302c31717ebc76ab983f0f21df084a1d3f8f83592b8213c7"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "991019b923b9c55b232afda68e29ab17bfa1750404219337643dc91d1512735c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.44-any-stack-060f349c.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "33a681f644795a10d5559186613357e56cd5a09660633d55062ff4622ccf06e4"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "1f6a1e796d0dbb10b8c87021562bbfbf698faa84a9da21b5586920ad6a387eb2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.54-any-stack-33a681f6.tgz"
version = "0.0.54"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "3859f9e874f30ba69fc7d36c5d5c4aca1d86e4ab393af96595f56285d41c45ea"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "4c628519ab6a8899f8f3888ca813cd066ca9d9fc5c4940dae19e2972bc7b2127"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.44-any-stack-3859f9e8.tgz"
version = "0.0.44"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.54"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.44"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.44"
