api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a0fa42031ceeb527ee734a3b81c4adac58cf59a01871e821a19b557a9a28b5ba"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "99379416efc3950a1232c89b4d335da94448f802bf333cd51c13c969f56db645"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.96-any-stack-a0fa4203.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "1e30185675257839e73df3adb6bab28e9f59390be94a83277800bac61db57cad"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "763bd2418f71ff8f71466ff8fd240dd58c237123f57386b2c35114d214ee9b5a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.55-any-stack-1e301856.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "f55ed98e62651c3b8f2a59916f4d60c525136dc19596d11b4a0aff75f6040707"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "eb52134b340baf06e20d301cc65b190cabc40da01d6607ff6efa723361cbbd62"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.97-any-stack-f55ed98e.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "1d1269929e21ace3d2b51f14054517e0d3e45d1faaef5499d6c59e2b6306ab70"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "d99e73b48aaddc8bbc7afafc1d66a99e3143ff87146f29630987b34a6abde433"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.105-any-stack-1d126992.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "50f52fd6b71fdb68128ce83e22e8a0e882c5205999fcdc88e68dd6034b5aad3b"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "36b4b0c6be57b7db2bd156bb2ee697001ca27c27cea3e76a9ee86a096afe70d2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.98-any-stack-50f52fd6.tgz"
    version = "0.0.98"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "be541dc990ddb5d2dd755ab537e07e00edd2380188c65e53d53751233bf08353"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.24.tar.gz"
    source_sha256 = "adb1e0d66166a07bd1561b00374af71416bdc792c40e39a24c9552330713613d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.24-any-stack-be541dc9.tgz"
    version = "0.0.24"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "4a99f6d5a2ec4d0ec71b09bebc89f4ec936ce512dfcec4257c2a1fc618470d9c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.132.tar.gz"
    source_sha256 = "91eabc098cab690e45411904239b4a0417fe76a7396b251020b35c0ffe387ca9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.132-any-stack-4a99f6d5.tgz"
    version = "0.0.132"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.132"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.24"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.105"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.96"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.98"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.55"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.97"
