api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "4f267a1d8c0f0986bed30469025ec8a0717fd677e70d9e3711bc9786c7de2652"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "5e70059168560c009fea7b3c584974a3b4d033c98d9718ed27bb4be7f4d1e49f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.83-any-stack-4f267a1d.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2789e767b7f9311f82705ca501f53efc8e5e014e7d89306c053645e3f572c66d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.42.tar.gz"
    source_sha256 = "64870a19bc4de687f9fa7e33204476520c204e88a3892fa6e3eee11ad582415b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.42-any-stack-2789e767.tgz"
    version = "0.0.42"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "43ae5cd76abd294ef63093cc8a8022a1e525252cbc6edfa53cbc4a71ca16f171"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "075b3157f63a07c6a9ae679d318f793b13d38be8ce3fde0b1a70676b22d7b8c9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.84-any-stack-43ae5cd7.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "7f45a2bf1fd460662aca48fb6d9f49b5a547eddca46a73d6e59587adc2f7f709"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "df9cd3fb84506f3f387c704201451141f53c22dc9e345a76ef77356416c8ec4a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.92-any-stack-7f45a2bf.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "0c55a413bd6c725e5a2343b9efb7523d33328aa2b4a3f90dcbc24023a5aa622b"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "2cf5aa2eb2f96df350da592e7ba6775b1321fb6b00ad735efe3dd1afae4cf2cf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.84-any-stack-0c55a413.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "73e0c9ea2a4aa389e7c20e1bff476e8dc0e58774d51f865a44537c85b636338a"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.10.tar.gz"
    source_sha256 = "d86e9e649565c00aeebbd89704aaeb8eb95637dce6d1a1bb728a532b9ca90652"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.10-any-stack-73e0c9ea.tgz"
    version = "0.0.10"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.10"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.92"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.83"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.42"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.84"
