api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f80bb5acf5663c758e66d928c3ff11c5f6fc1e5edb991658a9a000bb91af3158"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.34.tar.gz/archive/.tar.gz"
source_sha256 = "d8bc24680ee5838104c44961cbc15f78d24310f869309c7af5b7dc3c186a05e2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.34-any-stack-f80bb5ac.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz/archive/.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "3890da56246703b882c17bbad137e78d2db626edbc46d085d5dab7a8e8d17842"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.39.tar.gz/archive/.tar.gz"
source_sha256 = "52285c9d0e72bbd0c8029747a4d0fc0ba1f6097b4927092810ca9f8f26d71f5f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.39-any-stack-3890da56.tgz"
version = "0.0.39"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "6a16b089ae58d2c08378ba75ad191d3d46e3652ba0b6958c08f5d398460eb3fa"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.47.tar.gz/archive/.tar.gz"
source_sha256 = "e6cfe5dc3e8397d4a2d35148962362b7f9ade48ee1a424c255fafeb5ab8cd8e3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.47-any-stack-6a16b089.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "92e568b3ef0f0854c0572ab232e9d4d0cce14415fcfcccee4e0bbe68aa13cb18"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.36.tar.gz/archive/.tar.gz"
source_sha256 = "b54cd0866268f248269253a862b87827b310913cd20d98b2d859e5e18525ec62"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.36-any-stack-92e568b3.tgz"
version = "0.0.36"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.36"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.39"
