api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f3246445de1acb583b4ba037db208d67eed403a78cc44c18b836896c315f64a8"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.15.tar.gz/archive/.tar.gz"
source_sha256 = "14098480d4b1e5079b6d945e3155f1243396a70929e4e1ae311bbe6228086f4e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.15-any-stack-f3246445.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "4a82bd73f0483ae9a1f8c82721cf836f39628759043adbcb81efc302e158b3f4"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.24.tar.gz/archive/.tar.gz"
source_sha256 = "47da0b141cf9187e2ea2b65a244d17c2736439a6f8cb0001d0ebc5de4ee92fcf"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.24-any-stack-4a82bd73.tgz"
version = "0.0.24"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "898b25ee46584dca283b7f8eea8edd10f1e0278bfa46a2f0b630c30e36f532f4"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.19.tar.gz/archive/.tar.gz"
source_sha256 = "24fa161277a237f38f4b45b35ddaf9aed089af792ba689df74915b8c8f411fec"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.19-any-stack-898b25ee.tgz"
version = "0.0.19"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "6adf11354efa91590381c1f821d94ab3b50cca73c05f2effbdf883cbdc3a6170"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.11.tar.gz/archive/.tar.gz"
source_sha256 = "3372a7ecef708c6b8380621aec37f312703680ce4781c99aa4dda55413af9b35"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.11-any-stack-6adf1135.tgz"
version = "0.0.11"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.19"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.11"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.24"
