api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "393cbe076e2c819a157908d680f25a4527a1f2b4018d16d9e0b54b6fc1dbca2f"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.29.tar.gz/archive/.tar.gz"
source_sha256 = "4e00cbc98b64189c742d153e5af78246814e78d2459aad5222a2ed33efeacfbb"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.29-any-stack-393cbe07.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "a0b92ef8c8a413c8de67ec4ae75a4c88e1aa5c1acacdc55e5aadd38a3c8f6029"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.5.tar.gz/archive/.tar.gz"
source_sha256 = "5f12239c3a28c5b7673ee2c4a0424a5673921ea34af68dceaecfa32ef14220ee"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.5-any-stack-a0b92ef8.tgz"
version = "0.0.5"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "60b98fd5b818b49bafe1b5d334b1615683ec22a565d65aeaf1a66bc5fda420de"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.34.tar.gz/archive/.tar.gz"
source_sha256 = "e6dd37979608902205adee9f4a62cbe42c5b6b7c19a0fc4f25851fb752b26f2f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.34-any-stack-60b98fd5.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "c8e7ceb0ae0e6aa9b8a495f70a690f913739ba1499bb588e544504114033cccc"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.38.tar.gz/archive/.tar.gz"
source_sha256 = "66e49b7776781b55035a21b3cc558fb849d702342361f2afda8964ac64a4fa7e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.38-any-stack-c8e7ceb0.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "260dc44422ef199e8db6c86d7bc864e105075a575a6d5e38130c6addc4df2f46"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.29.tar.gz/archive/.tar.gz"
source_sha256 = "1fe5e482f07ea3419c1eb0ff6db64f63edc6d56dcdae39ea5267cee574eb29a0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.29-any-stack-260dc444.tgz"
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.38"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.5"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.34"
