api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "754da937ccdad0a58e2270352bd8547d833a83bb4d059c624fa407c71df7a577"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "4c54d289a9defa281a1058573819cf2c2e9d37ce42319358db5ca80dc686af1c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.42-any-stack-754da937.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "503e18964274f3f54e0289055e3635f60f92160af9e981e74191e3ad84eb81b1"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.8.tar.gz"
source_sha256 = "a1f760f881bf66fd34f76a67b7dfa1ed42f503c2f591d0fbd0686c0e15f8f3fa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.8-any-stack-503e1896.tgz"
version = "0.0.8"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "7bcdab877da4dc4baa5c6b8e7d43519dc5ed9dca2c8fa2ab222456c4642dd388"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.46.tar.gz"
source_sha256 = "6028324ce167f83f61edac17f7e36f2706c7ca9066debbea1a95f469f9525fc2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.46-any-stack-7bcdab87.tgz"
version = "0.0.46"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "5c29729d52d58c840934265db2fe610e0e3ecdc9c12757f50c66c9043fc8bae8"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "4abce4f8437bf7cff755c91ccf6c24238da8c8aed8e1034366d7d91fc27b72fa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.55-any-stack-5c29729d.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "de80860736f7d1727d301b05463a35e6a5a54ef502655432d476506b075324e5"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "60b0c8ad47915831257aeeb11840afa4e46098aec9826d12a55161658e36ff5f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.45-any-stack-de808607.tgz"
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.55"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.45"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.8"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.46"
