api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "9f0055cded3e1eb27d1b10b776ad873bbc2ab1b4e5370ca6c9e45e7140e39711"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "7de8ebdf6f847f54dd60c0c76b118ac44583fba70a4fe48e1c16333fae1abbf2"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.48-any-stack-9f0055cd.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "a25d6ee70f61e903b651b4510cbae5e86e417888ff3dc27081a180157d1ab655"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.13.tar.gz"
source_sha256 = "d0bbfec9f9a006fc8fc79b802ed7a25d6364874b3546f5b1d007a8a15cfccb1c"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.13-any-stack-a25d6ee7.tgz"
version = "0.0.13"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "7bbdaf1771c5e61adf499f07ad37036dda9e7f3f03c9f866087aac57b7714180"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "ba7a6d93fc9709721e764b2ec4f2122d9c73630755cf1ed6a0924226d7899080"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.50-any-stack-7bbdaf17.tgz"
version = "0.0.50"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "53726f2dac478d5442bed6aa64eb80d3b292d04a018d347f4ce47d922332f9a5"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.60.tar.gz"
source_sha256 = "4002565381e93ce2fe1f905e47adb8aee284b6087b05c7b5996709c63044963c"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.60-any-stack-53726f2d.tgz"
version = "0.0.60"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "3481492e5b8264223d97b736a4295aac36b317a5582285cc94c7b7c1485451aa"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "cc66beb953b483f2b4d1d23099586a1f3a554bef08acb1be3c36a2103cb12e19"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.50-any-stack-3481492e.tgz"
version = "0.0.50"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.60"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.50"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.13"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.50"
