api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "f788ae888162156b1caa14e76e39ded322d507ad725a2cae65144d430bdec18c"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "232f067fe636955b9fbfd282cd1647a4e93075a777d267c7b25822119351a87d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.79-any-stack-f788ae88.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "b492fa4cdcae5ca1e0a4a13f34cc6a1a0fef791e9b3fc6be78c7df6d74bd91bf"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.41.tar.gz"
    source_sha256 = "26f673905606ae6f7d19e6b1f2e7aff93a61bd4e585a864398fe20c8fc7bca73"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.41-any-stack-b492fa4c.tgz"
    version = "0.0.41"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "268b08d59b9a13c19964256d70a2cdcb4cfe7a970f3302c75e9fac71ce099f04"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "59a5c5d38fdbde1b404adea5c04b905a69830097ed3a3933bd3be37c603aee1d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.82-any-stack-268b08d5.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "f21ccb28cf233c36e7f2376e3d0f13e61ceadce992924788d41ee1dc6060ea58"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "0f4d3e7e15b6d4eb63a86124d9a836b2c23c3903277cd5de1220bb971aa4d1bc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.87-any-stack-f21ccb28.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "a9c4660119adf065383458e229f67cb664e7bf6b2bffd7d964367cd24ebd0409"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "89eb6a5f76c8b005a0219ead0879fddc200e1c8a5108ca3d9a015f8e3c2330bb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.76-any-stack-a9c46601.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "963b6d98ead85f5e32fb3b66f74143cc106db6a5ec238eddf53e6ec8a1f69279"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.9.tar.gz"
    source_sha256 = "bee58760d864d63e3387e6675607e0196b044937107d3f578f09aa059d5be695"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.9-any-stack-963b6d98.tgz"
    version = "0.0.9"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.87"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.79"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.76"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.41"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.82"
