api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a8d2193acfa5d59707e348437ba0974312dcf5ec2ca675f30780cfd2b0dfcf5d"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "0b5aee17e388fed32ce934d93d9113773f59189326c27d668c5e78a1947f0f27"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.59-any-stack-a8d2193a.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "ea4faae905ccac791fea3e403b1b4a322736f689189cb7cb839a4258000cecea"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "bab906efafe8999d60855fda07d0c569121cd7a961ce3b3a162b5d3068c888ed"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.66-any-stack-ea4faae9.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "ea4faae905ccac791fea3e403b1b4a322736f689189cb7cb839a4258000cecea"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "bab906efafe8999d60855fda07d0c569121cd7a961ce3b3a162b5d3068c888ed"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.66-any-stack-ea4faae9.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d6907b288191140b499cacc9f8d0b67b2021bbbd6f9f63b93a447bfae0da01c1"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.24.tar.gz"
    source_sha256 = "41d094fa56fa554d31937a9858f66a91b224a79d157e035caebbaaefccb0b576"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.24-any-stack-d6907b28.tgz"
    version = "0.0.24"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "014fac75450dfc584bf09745715f6bb4e8ea3fc44299db493747b778e3996269"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.30.tar.gz"
    source_sha256 = "d878e21a014f1ceae2c67fa1a01fb1f75da2bbf40edcf3a8f3e3f7bbf249c83e"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.30-any-stack-014fac75.tgz"
    version = "0.0.30"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "014fac75450dfc584bf09745715f6bb4e8ea3fc44299db493747b778e3996269"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.30.tar.gz"
    source_sha256 = "d878e21a014f1ceae2c67fa1a01fb1f75da2bbf40edcf3a8f3e3f7bbf249c83e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.30-any-stack-014fac75.tgz"
    version = "0.0.30"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "14ab1823e9baba1a4c2ca1e137fe5b2a262efe1448a67884b1c4cf42901e329e"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "4889ff2c347efcdd5c5d4f1da84569f2e8fa17eb207681f72c47907613329606"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.64-any-stack-14ab1823.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "633c8f736ba072052ac1ce5f95ea22329a8dc7b8629a1d7850f1759d069186e6"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "f0024095bb3063855075ebfcea65458b314368dfe58cf998c3a30c34815546b0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.73-any-stack-633c8f73.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "633c8f736ba072052ac1ce5f95ea22329a8dc7b8629a1d7850f1759d069186e6"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "f0024095bb3063855075ebfcea65458b314368dfe58cf998c3a30c34815546b0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.73-any-stack-633c8f73.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "09cbe1de1f7ece28b0f0f3b6bb01672386c8589781f430bf1edfae7515709cdf"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "e7d2073c5a0b33fbceb73d66b17210f9cbce8af0460f0af78c91967c2c5d1597"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.72-any-stack-09cbe1de.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8d45686afe4867d7f2d490fc937a85f515f00ec6ffff4d74f7b27323571b49d4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "0ecef56c36ce82bf07ca60ef7ede934ab5ca8c0895dbaf1eba9c78769850bd8f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.78-any-stack-8d45686a.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8d45686afe4867d7f2d490fc937a85f515f00ec6ffff4d74f7b27323571b49d4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "0ecef56c36ce82bf07ca60ef7ede934ab5ca8c0895dbaf1eba9c78769850bd8f"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.78-any-stack-8d45686a.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "d68abde46d36b024f577718bd93965153161285050e480c169b750194caa6833"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "0c1c9f2ec0bb324fd565b5d7015a5a412214c61c967b9ca057b6a834f93f1f1c"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.62-any-stack-d68abde4.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "4cabbbc29f3314ef144158d5977e18c72d0006a46c744187e61ebc35cbf2be89"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "e49c5706cfbdb7f07e57a069b6857caeba71c1f90602ea1e95518e14e05b6304"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.67-any-stack-4cabbbc2.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "4cabbbc29f3314ef144158d5977e18c72d0006a46c744187e61ebc35cbf2be89"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "e49c5706cfbdb7f07e57a069b6857caeba71c1f90602ea1e95518e14e05b6304"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.67-any-stack-4cabbbc2.tgz"
    version = "0.0.67"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.78"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.66"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.30"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.73"
