api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "c6d9e5f4ce312840b84a1f2a58764469b5306e531474f5edb0fd2b0c02b9bae0"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.30.tar.gz/archive/.tar.gz"
source_sha256 = "746ca2156b5ad674fc7ecc0d3243438246d65c04af0a34e42659803b77ebf317"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.30-any-stack-c6d9e5f4.tgz"
version = "0.0.30"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz/archive/.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "769760be5c3a911e0ffd5d6ae90fb3cecbdc3293cae5a1f5473ef2bba1dea9c3"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.35.tar.gz/archive/.tar.gz"
source_sha256 = "d0bad8b7b388c67b99ea9a6b3beafa213c90c8b83154f805567ee28850948f07"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.35-any-stack-769760be.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "c8e7ceb0ae0e6aa9b8a495f70a690f913739ba1499bb588e544504114033cccc"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.38.tar.gz/archive/.tar.gz"
source_sha256 = "66e49b7776781b55035a21b3cc558fb849d702342361f2afda8964ac64a4fa7e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.38-any-stack-c8e7ceb0.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "260dc44422ef199e8db6c86d7bc864e105075a575a6d5e38130c6addc4df2f46"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.29.tar.gz/archive/.tar.gz"
source_sha256 = "1fe5e482f07ea3419c1eb0ff6db64f63edc6d56dcdae39ea5267cee574eb29a0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.29-any-stack-260dc444.tgz"
version = "0.0.29"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.38"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.30"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.35"
