api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "a9da71698d8ecd8fbb7c322d17350912d00a62abbefd97a93802bc827a6ee162"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.53.tar.gz"
source_sha256 = "14153bac739a6e03bc41135ce40312520c7b93b5af1277ce6085ea95bfed3d14"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.53-any-stack-a9da7169.tgz"
version = "0.0.53"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "bffc881f945427d2bdefdda610a9f21dbfd66b91b80e1d94bea9006c2e5f0270"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.19.tar.gz"
source_sha256 = "4b10db435b6028474882ee1d04628f6c7acd8f11eecf17416ba4649a6a90a016"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.19-any-stack-bffc881f.tgz"
version = "0.0.19"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "e34ceec7c865669903b3dd77b835f289053a4aeceaf63c865a4264488c320a3c"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.58.tar.gz"
source_sha256 = "da0a7aaf88bce20e0095f5cd0290aef3d8485be6494e4cb7854d3837a890eab6"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.58-any-stack-e34ceec7.tgz"
version = "0.0.58"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "40caca3fa15a3d9634e9573305daea326354800d9682f8d4c43107b3d6f29307"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.66.tar.gz"
source_sha256 = "2f4eef721d6600a5bcae81b75996c2fbb0c52d28b8d288b33616153d4efff7fe"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.66-any-stack-40caca3f.tgz"
version = "0.0.66"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "fb23930b91ceb9c83dbca10fb7f3948bcdeec97f862c3a815dcce7b7c09c4a2f"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "608e52f7c8813ae6a8ccfc5fdb279fb73b13f3ff21a8f225224a0618a02ff91f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.56-any-stack-fb23930b.tgz"
version = "0.0.56"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.66"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.53"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.56"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.19"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.58"
