api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "76fede84da9b8f4aa2c72b6e9f1978cfc713073daaebe1d596d77dc0487a088e"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "315eb4fb47b96932dfaa643dedc378b726a64ca5f3021ea4dde32348323a9126"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.103-any-stack-76fede84.tgz"
    version = "0.0.103"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2525bb7a9bc27af976e45ab387ed899b2f3a749168cc4e25d913b8a10cc4ed05"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "abcf8870d10846624c3d87cdf0958a2257d476fe29c17889f0d876bbfb5a7cb9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.57-any-stack-2525bb7a.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "babfedcec5b6aafb989911e866f1ead1eb95e84bc8052455c710f091d5732c6f"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "21adba9ed660c4e6a44a4f27c1907908d6a9ba01115fbcf0a311fd7a8fa1a5bd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.102-any-stack-babfedce.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "10a06dc20b1d460c1283ef16710d3046c76ee8d130b1c20ef4d94fcdfad337be"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.113.tar.gz"
    source_sha256 = "cbe6e6c84d44d09a6c0e96302f6f9783b37e6369f7f1a5318a7c1a92cc48d793"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.113-any-stack-10a06dc2.tgz"
    version = "0.0.113"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "03d9a8e783bacdbaed55c168a6b8af5635b42507a279a1dc278d14014407238b"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "42629c6a5bdfa013996d66bea229adb9cf9844fbb97304f5b4b953de63b7623e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.105-any-stack-03d9a8e7.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "ceaf520d0f7279fddd92d70df4e037032d1f9179b3c7de16c565c43523a74f15"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.29.tar.gz"
    source_sha256 = "7b04616dbd63e13059341e9254a52fa693382619ff7ee375e813303fb29f7c0d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.29-any-stack-ceaf520d.tgz"
    version = "0.0.29"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "92c185d9ce90742e4afce8c90a43913c5f2003f33c384fb0e29be07b3ff0c022"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.143.tar.gz"
    source_sha256 = "475e12db82a1e7268d61a21daf65959582f0902f3219e5404e971c4312aaa8fe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.143-any-stack-92c185d9.tgz"
    version = "0.0.143"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.143"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.29"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.113"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.103"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.105"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.102"
