api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "173ae8d89ec5cff4acc59329eaa114fa1b939010c15d6f2189fe547064632c94"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.23.tar.gz/archive/.tar.gz"
source_sha256 = "49b31f10daa539f7cab255b40fb597fd475f71691cca74650b2f736fe2d837b3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.23-any-stack-173ae8d8.tgz"
version = "0.0.23"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "31013590eb9f297ceef1d761326021fba5bcbf3dfcfb7c2abf089bceb5862d43"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.3.tar.gz/archive/.tar.gz"
source_sha256 = "53f4849141a58f2beb119beeaa91291eca3d20e26fc7bac75740b4ade035d0e4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.3-any-stack-31013590.tgz"
version = "0.0.3"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "aed07f8364c78d5c4fd193da48029f607641cca6d75bb280bea3d49cde912d93"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.31.tar.gz/archive/.tar.gz"
source_sha256 = "627f0b7357e40ecafb2e96c77ba5373e542c25ef2b63838c4fc55fe4eaa4eee8"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.31-any-stack-aed07f83.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "6fbf70ac3b52f73d3093d72dbc5fdb8369f1596675a13fb11ae5aff8b3dfcf8b"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.29.tar.gz/archive/.tar.gz"
source_sha256 = "8f19706a3d9e6ec787d65ebb312c945a094aedd71ace0f43dd73746a7bef5c69"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.29-any-stack-6fbf70ac.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "9bdaf214d481069c601e381774ac84692e7652c3acd2b5dee6e2ea37b22a3d23"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.24.tar.gz/archive/.tar.gz"
source_sha256 = "1615a9031e83cdefd5f98d0bfd4b3ca451b25aa817fa9ca9db00111908d5c1fa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.24-any-stack-9bdaf214.tgz"
version = "0.0.24"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.24"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.3"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.31"
