api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "03f7e69ed617beafbb174ae51cdd823878bfbe1dc1650c8586ffcabbad13d916"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.39.tar.gz"
source_sha256 = "ea07d8ad509164979f1618f025d2aa8cef65b70d0c91420017e8484e0b82974b"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.39-any-stack-03f7e69e.tgz"
version = "0.0.39"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "45edab7c549ba9c1d48b967375fd89fdccc13753c496deb04c00a97f93202bd5"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "63a7371ff5a14b1b8ce74f08149477254f69727e576fd7e473d3ef58f147d140"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.42-any-stack-45edab7c.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "7dab3a35e4ab356fb1df62e6afa8f5a0a5e5bff16bddd0cc8bdee21ae628e313"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "c7506b46f70539237afbdec41be00151c2111895f6d0f33c4f18f3ea41fa42d0"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.51-any-stack-7dab3a35.tgz"
version = "0.0.51"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "c4540870805eda709b48c58700b638332b3ffb587dff5747e1935a13a6b182e2"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "db4a23b947b2bb48e31c22e39ee7e86e175b7321edb2f78127e67276b5d9097e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.42-any-stack-c4540870.tgz"
version = "0.0.42"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.39"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.42"
