api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "c4af14aeb184a35068001dcdd9c000be5ad20380c7870611f9a7e40b96c90452"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.118.tar.gz"
    source_sha256 = "ff281acd00741453cdfb42f41a03d3510cae976044a3bf48c844aa5c059d5f82"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.118-any-stack-c4af14ae.tgz"
    version = "0.0.118"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "4349ccd18bf38a63cc447d47ccb326234afb645cf122d276fbcccbc21c00b07a"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "87b4f9c1d8bfd723b434a05dcb6cc538d542171e964a02403ad8feb419adee97"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.68-any-stack-4349ccd1.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "2a6d1c199d41d487157cfd6275f9c31189e56b908f5a8af2d604cb0a71b6227a"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "f60fecdd90630ac3a009756a77d885da0fc9ac0095424a1a0465d123a9a8736e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.115-any-stack-2a6d1c19.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "af380f87fd65690ad9d5431cb091a68518d4dc14262ad3e9cc76112b763104ff"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.127.tar.gz"
    source_sha256 = "c7c9c446e369bd9ab9a5928c095aae8f9fcb6dc4e0ad71e4f26adacee06ae401"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.127-any-stack-af380f87.tgz"
    version = "0.0.127"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "47de032e1d7c09849a4d7247c4f7bb19d897cfdd4e47f609883aa2ab843842ba"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.122.tar.gz"
    source_sha256 = "3324b5cf871d931c355dbfdf9c79aa44135bb1651001ab9a1e58b6db39a536ad"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.122-any-stack-47de032e.tgz"
    version = "0.0.122"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "6a71321d1d096ffec72acdc707932b3e3364fbbadea45741513db94bab82be71"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.43.tar.gz"
    source_sha256 = "8a3ab36445d674c108d155262666b1dd9efa084a1dd9b1b98a8c3898a0e531f6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.43-any-stack-6a71321d.tgz"
    version = "0.0.43"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "2b9cea9e9bfc3c9dd4f12e3b1f42b199fd50d68a3fdf85f9346f519973be9d4b"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.158.tar.gz"
    source_sha256 = "09982a99cef8d8b7012ec2ae2afb0fcf12bcb799eaec1593488b8fb95edf1687"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.158-any-stack-2b9cea9e.tgz"
    version = "0.0.158"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.158"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.43"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.127"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.118"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.122"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.68"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.115"
