api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "0a1f6f99f89760db883385070b266951f49efa2158cf82c919c98d15c6ad7f12"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "37ab59033a14913598de1a3b7112f90240c309932ef85aea61acd11bd8ca8b46"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.102-any-stack-0a1f6f99.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2525bb7a9bc27af976e45ab387ed899b2f3a749168cc4e25d913b8a10cc4ed05"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "abcf8870d10846624c3d87cdf0958a2257d476fe29c17889f0d876bbfb5a7cb9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.57-any-stack-2525bb7a.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "6e4eb3e611b5ed11fd3f3f9ee761df53843b7d44e0b7167d34a0269d9c2c0cae"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "d43af22db3c1f912cf4ed6f895d618d0cac1ce12553f9bd23831847ace511255"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.101-any-stack-6e4eb3e6.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "b14dae4b0ef8c4c7206fecbce1bddd6171e5563424d8711d84d18b1226d8709a"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.112.tar.gz"
    source_sha256 = "54fb6cb4429aad11d7ad343e961c9a6cad26144c03f44365570b6590b5327057"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.112-any-stack-b14dae4b.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "690dc2c06944f6e4eb7a1c837710356897e12b0a4cd4e6438d425500df6966d8"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "928b99c224b12a6794a0345aa33175d4425e5b50020c299cfd5c9271cc2fb650"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.104-any-stack-690dc2c0.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "1e97b4d5b62fe93024939ff87cb91fd8ea6ffc58e1b6f666c3e4d4a275d4d5ba"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.28.tar.gz"
    source_sha256 = "b472cb64ae63fa7bd1395f27c18df5291e621949b7ce817b471896c868ab9259"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.28-any-stack-1e97b4d5.tgz"
    version = "0.0.28"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "92c185d9ce90742e4afce8c90a43913c5f2003f33c384fb0e29be07b3ff0c022"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.143.tar.gz"
    source_sha256 = "475e12db82a1e7268d61a21daf65959582f0902f3219e5404e971c4312aaa8fe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.143-any-stack-92c185d9.tgz"
    version = "0.0.143"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.143"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.28"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.112"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.102"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.104"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.101"
