api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "bf12d2168dc445045737b7ae10ff6ded8fd849fd9d72839af6e4a3669b91755e"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.112.tar.gz"
    source_sha256 = "a743daf90e477a2a7f730406893faa66876cd880095afafd04203b8588daa42d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.112-any-stack-bf12d216.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "ba9d09cebf99509486d6be7c5813d0ba761b42c7551ce6234c1d2f1ee2461fe9"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "e377b38fd341fb6157ddef6494eda6be46181f2539fd8b57d6766def4e1d254a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.64-any-stack-ba9d09ce.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "9b90255c04144d7b1addb12331c9f145ffb0ed96927ff5eb0ff264bf524621f1"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "837ca3e3ec8abf5f69ef6bab034423005239228bba048ddcc89204f3d4700ded"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.110-any-stack-9b90255c.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "f8f75d7a4f2729093b9a18a1b3e918c326ff07fcd5bf391abc067d7f5ea34e38"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.122.tar.gz"
    source_sha256 = "4c93f76242181f392e9b79e35af7968407b9d6b729bef9c95bdba4e0cbb47849"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.122-any-stack-f8f75d7a.tgz"
    version = "0.0.122"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "61d98f2763ad3ec8a94d84f5c9d8ddec8862d7291d352b587644e0c37f1bf8eb"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.116.tar.gz"
    source_sha256 = "44128df89e7a5eb0056d22fb856d2b35369bab3f13d7337892d18913d3775a0c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.116-any-stack-61d98f27.tgz"
    version = "0.0.116"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "b11787055bb5112210bfed5f3a0a27a5cfcbf8b36c8a38da16e90e05c8c4c560"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.40.tar.gz"
    source_sha256 = "afa517fe4614c2c4e6fafd081d22da04476ddadef71b59477131436b538735b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.40-any-stack-b1178705.tgz"
    version = "0.0.40"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "85e93f4e818ddb0dfc6e4bcf5130291dd6b74c9c4394fc124dda1e9e9851f79f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.153.tar.gz"
    source_sha256 = "1907503b7d82aff117f9d6fd5f1c42e531337b157093a5525519df1af9f5a5ae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.153-any-stack-85e93f4e.tgz"
    version = "0.0.153"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.153"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.40"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.122"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.112"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.116"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.64"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.110"
