api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f3246445de1acb583b4ba037db208d67eed403a78cc44c18b836896c315f64a8"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.15.tar.gz/archive/.tar.gz"
source_sha256 = "14098480d4b1e5079b6d945e3155f1243396a70929e4e1ae311bbe6228086f4e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.15-any-stack-f3246445.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "a4fc27c4cca9b0d84864714e6dd8d18af405af4a50f5785cc905f2ed26d18850"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.27.tar.gz/archive/.tar.gz"
source_sha256 = "232f86e4f2fedc9460801310b32d23c6aa746e19a1d1a62b852383e535bf1824"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.27-any-stack-a4fc27c4.tgz"
version = "0.0.27"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "898b25ee46584dca283b7f8eea8edd10f1e0278bfa46a2f0b630c30e36f532f4"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.19.tar.gz/archive/.tar.gz"
source_sha256 = "24fa161277a237f38f4b45b35ddaf9aed089af792ba689df74915b8c8f411fec"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.19-any-stack-898b25ee.tgz"
version = "0.0.19"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "3f813b5f12918427a5db93820be86afc74dbb144143c046c220edd9b31a3add2"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.15.tar.gz/archive/.tar.gz"
source_sha256 = "8d8f3238d03dfe56839607a73237251e62a4eec4dd68b7991ad185ff01411d32"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.15-any-stack-3f813b5f.tgz"
version = "0.0.15"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.19"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.27"
