api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "3c95fbe07d9391bf98fb8a57d169a23d727fed4a492588420a4d2c5e5f70133c"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "d8d0e795ba5d7bba01026c46ab5fc492e3b6a623192d1d96b1d078db15dd4080"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.95-any-stack-3c95fbe0.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "14af63d9e5b7dbb6eefeb4f1ec83c71e6751794fcbd3b122debc7c309fc28f91"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.54.tar.gz"
    source_sha256 = "43878d1a16879950174812c314166fd97642127956f142361a3c255db71bbed3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.54-any-stack-14af63d9.tgz"
    version = "0.0.54"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "f55ed98e62651c3b8f2a59916f4d60c525136dc19596d11b4a0aff75f6040707"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "eb52134b340baf06e20d301cc65b190cabc40da01d6607ff6efa723361cbbd62"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.97-any-stack-f55ed98e.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "1d1269929e21ace3d2b51f14054517e0d3e45d1faaef5499d6c59e2b6306ab70"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "d99e73b48aaddc8bbc7afafc1d66a99e3143ff87146f29630987b34a6abde433"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.105-any-stack-1d126992.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "50f52fd6b71fdb68128ce83e22e8a0e882c5205999fcdc88e68dd6034b5aad3b"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "36b4b0c6be57b7db2bd156bb2ee697001ca27c27cea3e76a9ee86a096afe70d2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.98-any-stack-50f52fd6.tgz"
    version = "0.0.98"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "be541dc990ddb5d2dd755ab537e07e00edd2380188c65e53d53751233bf08353"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.24.tar.gz"
    source_sha256 = "adb1e0d66166a07bd1561b00374af71416bdc792c40e39a24c9552330713613d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.24-any-stack-be541dc9.tgz"
    version = "0.0.24"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "00e0e332828ca0f780fe62a3f29bd4e8854672135d55bf06075df97706bf0a73"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.131.tar.gz"
    source_sha256 = "b6150bcb6213b85a8d89491f5d516db568ca6afa21a2506116f77f9cf0780b75"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.131-any-stack-00e0e332.tgz"
    version = "0.0.131"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.131"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.24"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.105"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.95"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.98"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.54"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.97"
