api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "b304cef86bd0008e51b32552b87e4bc48eecff2366d6977ab229d1a0fe89cdcc"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "12bdd85e14f23fc1a1e5293c115cd78d0f50c7ce5b644fde4832504ffcf9faef"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.101-any-stack-b304cef8.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2525bb7a9bc27af976e45ab387ed899b2f3a749168cc4e25d913b8a10cc4ed05"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "abcf8870d10846624c3d87cdf0958a2257d476fe29c17889f0d876bbfb5a7cb9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.57-any-stack-2525bb7a.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "dad3127377120a66497ca5ba1d34161dcfff071d3c788ea83506ba45696cd1c5"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "2d24e6385f6a18b5a04c9de1759e0bd9de6be9e48c20b488e7613d990cc7648c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.100-any-stack-dad31273.tgz"
    version = "0.0.100"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "e20662fa49ca11e2f4b8a7be889f51e740d570f1ecf811c58ad8281c632ed8a8"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "968b90b57c90feee0a3192e6cfcdc7c05abc59e7e83e01700129d826c4002672"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.110-any-stack-e20662fa.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "9eddb071c26782edb876c616376cbb3fd596da0e8c70d66c18f3c3ca5541e172"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "a3ae845b0680b34d33fbee650bc1e911c93742d659083255f6ecd00ef4bb229f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.101-any-stack-9eddb071.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "9d9e7ea1bea240d0f9038a70ccd7c3ca4d9936d2e53d9e524c387902548fd859"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.26.tar.gz"
    source_sha256 = "b5d079dd9d37b6cb5f60849b45128ca88498b4284e5bdf5dc248dabe0db3cd48"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.26-any-stack-9d9e7ea1.tgz"
    version = "0.0.26"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "5aec7293ab8dbf32fc6e4d8e06a4b4310672f84144f5a7be654b92a362caac2c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.139.tar.gz"
    source_sha256 = "d05594a5e1df4687ac7855b5e41edca8ea84681785d4e84b8f1deda8e988ff7d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.139-any-stack-5aec7293.tgz"
    version = "0.0.139"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.139"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.26"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.110"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.101"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.101"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.100"
