api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "90dbf9a0dc5ec67184bd4b7b09a3f010295875dcc1eea2187ad4e3ba3e457753"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "bb0669bb8e10ab81149a54c4a60aa1318b923d548a866dd8f11ed2eb86379b7c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.89-any-stack-90dbf9a0.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "8d79010c8b8cfa97c5e7a0e35fe8f9290a2ae8b43c90847cc7fc158c0dee51fe"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.46.tar.gz"
    source_sha256 = "c476bd4fcf5f559f720e8373eb668171e036f2459a174756f1ed64fd5a415313"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.46-any-stack-8d79010c.tgz"
    version = "0.0.46"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "b378e29cfcf0c4d57667afaf6f506c7a436b7f7011ccc393ae682be3fe05c396"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "e912f6f91b9be2254c4263c487353612e33134b4e30a505aa9010dd801b5f677"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.90-any-stack-b378e29c.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "418c7e4e041a2b592b9ff60ffc9c1f50e1941d1258f370f92a26086b979a4ebe"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "7a38a43ad029e7ca1b53a64b3b29c7fd9e1e57d02293b01848eee3f1923a0207"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.98-any-stack-418c7e4e.tgz"
    version = "0.0.98"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "0b9474fd65d5adc2ed82942696baa6839ea45417f3931414aab8b840c29649cf"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "e72a934c149987b4514c96e9e6dc7d0a4381d76fe83fc40828eaff5201488aa6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.91-any-stack-0b9474fd.tgz"
    version = "0.0.91"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "5306d7de975b1c0ce55a9efed4806ba3c34566f0e67d815f3110faa7993fecf0"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.16.tar.gz"
    source_sha256 = "35c0c8d54fb71b1e9f76947395fcaaaff402a6d71be7cf92f269d8077c1c5207"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.16-any-stack-5306d7de.tgz"
    version = "0.0.16"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "cfb0fe7659ddd2f880d5897c82e137e0c9301727834433c13d8c5cb59ce263d1"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.125.tar.gz"
    source_sha256 = "f5634a8a028bd79b3cf71e0ae7c7b57bceb0e70d6a519cbde7a3d5a180306da8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.125-any-stack-cfb0fe76.tgz"
    version = "0.0.125"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.125"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.16"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.98"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.89"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.91"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.46"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.90"
