api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "173ae8d89ec5cff4acc59329eaa114fa1b939010c15d6f2189fe547064632c94"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.23.tar.gz/archive/.tar.gz"
source_sha256 = "49b31f10daa539f7cab255b40fb597fd475f71691cca74650b2f736fe2d837b3"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.23-any-stack-173ae8d8.tgz"
version = "0.0.23"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "31013590eb9f297ceef1d761326021fba5bcbf3dfcfb7c2abf089bceb5862d43"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.3.tar.gz/archive/.tar.gz"
source_sha256 = "53f4849141a58f2beb119beeaa91291eca3d20e26fc7bac75740b4ade035d0e4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.3-any-stack-31013590.tgz"
version = "0.0.3"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "eee424fdc4d755d62bbbb91e850886cea0c89faa0958c44ed4e1184cc1d942d7"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.32.tar.gz/archive/.tar.gz"
source_sha256 = "d48ce37e1f0508429c5475cb7e38e0716dc732abc914198617d6f24f8cf7a0fe"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.32-any-stack-eee424fd.tgz"
version = "0.0.32"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "a4763db1630e5680a86b1f48bb44c0c6ad01f792fc41d2348fab7923c7fb36c0"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.31.tar.gz/archive/.tar.gz"
source_sha256 = "f6da40146a2e8489b8cccaec2d83ea36efd795b6a73a3bb710f7c15f50d472c7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.31-any-stack-a4763db1.tgz"
version = "0.0.31"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "5f1bac396ecd1b76c83751f269ff071d3a1986066b9424a5ee8e4bc42da855cb"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.25.tar.gz/archive/.tar.gz"
source_sha256 = "794bb4e2fd043c4ff98c5a341680df1a27889634cb6c7d7016f1ff0640e493a2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.25-any-stack-5f1bac39.tgz"
version = "0.0.25"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.31"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.25"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.3"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.32"
