api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "0a1f6f99f89760db883385070b266951f49efa2158cf82c919c98d15c6ad7f12"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "37ab59033a14913598de1a3b7112f90240c309932ef85aea61acd11bd8ca8b46"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.102-any-stack-0a1f6f99.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2525bb7a9bc27af976e45ab387ed899b2f3a749168cc4e25d913b8a10cc4ed05"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "abcf8870d10846624c3d87cdf0958a2257d476fe29c17889f0d876bbfb5a7cb9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.57-any-stack-2525bb7a.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "6e4eb3e611b5ed11fd3f3f9ee761df53843b7d44e0b7167d34a0269d9c2c0cae"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.101.tar.gz"
    source_sha256 = "d43af22db3c1f912cf4ed6f895d618d0cac1ce12553f9bd23831847ace511255"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.101-any-stack-6e4eb3e6.tgz"
    version = "0.0.101"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "e20662fa49ca11e2f4b8a7be889f51e740d570f1ecf811c58ad8281c632ed8a8"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "968b90b57c90feee0a3192e6cfcdc7c05abc59e7e83e01700129d826c4002672"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.110-any-stack-e20662fa.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "868cab92fad51ecf2c5190e93468641a851340959d4d1612767780aa8096486b"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "b93b13f837c12f92f0b7c42afe4b8a51b5fe4a050d319e25a829783fb640badf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.102-any-stack-868cab92.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "1e97b4d5b62fe93024939ff87cb91fd8ea6ffc58e1b6f666c3e4d4a275d4d5ba"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.28.tar.gz"
    source_sha256 = "b472cb64ae63fa7bd1395f27c18df5291e621949b7ce817b471896c868ab9259"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.28-any-stack-1e97b4d5.tgz"
    version = "0.0.28"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "518c371c99c7d73003806e00f4de5951e144f2789f39806929f9d4571ad7473f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.142.tar.gz"
    source_sha256 = "61fa2a1d4f36d108189bdbac30cb5a90717dfd6b8d4ca3cf45faeb4c52ad5dbe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.142-any-stack-518c371c.tgz"
    version = "0.0.142"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.142"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.28"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.110"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.102"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.102"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.101"
