api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "9f0055cded3e1eb27d1b10b776ad873bbc2ab1b4e5370ca6c9e45e7140e39711"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "7de8ebdf6f847f54dd60c0c76b118ac44583fba70a4fe48e1c16333fae1abbf2"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.48-any-stack-9f0055cd.tgz"
version = "0.0.48"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "9ee499d5ee4c788781ddae8726e758697877bbf769c94422b43ef49d9ae6fe7b"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.12.tar.gz"
source_sha256 = "83b18b9cdeef5404ec405169a013a76f7d4e96d179ccb16f07868b1d78c4c4ed"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.12-any-stack-9ee499d5.tgz"
version = "0.0.12"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "7bbdaf1771c5e61adf499f07ad37036dda9e7f3f03c9f866087aac57b7714180"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "ba7a6d93fc9709721e764b2ec4f2122d9c73630755cf1ed6a0924226d7899080"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.50-any-stack-7bbdaf17.tgz"
version = "0.0.50"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "885438e94707a1a6747a05c58cf8e7972248149c27f8ddcb968abfd68b7ac7ea"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.59.tar.gz"
source_sha256 = "e0a75febd78e7e5a260106a10b7b44e7ce7c9a1cb7c9e5e153802c455137fdd1"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.59-any-stack-885438e9.tgz"
version = "0.0.59"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "12581728fa83ca5f9f1da2eb870ccdb40738f832ceac7110e202896cf957eb3a"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "48e7df30c4c2c1c7a8d407f890b2000a9728a6c2aba819785570e45da78abddf"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.49-any-stack-12581728.tgz"
version = "0.0.49"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.59"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.12"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.50"
