api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f124f4bc0aac4be847e0ad276db1dfd6fc9d9111ec848a600a7fdf49296676b1"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.33.tar.gz/archive/.tar.gz"
source_sha256 = "ffc643b1c6e2ae0abd5c94c9d620096950f2926e5edf1c9b15089bace25d8172"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.33-any-stack-f124f4bc.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz/archive/.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "ab78cf008230f491bf652bb1c0812226e486e53fbfe336deaa8c7da020cd102b"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.37.tar.gz/archive/.tar.gz"
source_sha256 = "2c34171e2e2a1fd5c96a60eaa0f96c7c17d8af586163ee2872f4809c251ebc9c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.37-any-stack-ab78cf00.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "28aa0c8603fcf78be9a1fc573a7ffbf13992e162001a6dd3c98f93646c8e5929"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.41.tar.gz/archive/.tar.gz"
source_sha256 = "32a216adddc6bb6167e4ce1c2dcd924cea64d2678e205525d582e91e705ebfce"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.41-any-stack-28aa0c86.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "24fa010229424ce7d3c006845b44cf7975a8871a5a7e432e8b461f8158ea3b7e"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.33.tar.gz/archive/.tar.gz"
source_sha256 = "385797a89037590f4d34c824b28856b6495d5534f3accebc0b3d33d3908dec3f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.33-any-stack-24fa0102.tgz"
version = "0.0.33"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.41"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.37"
