api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "50435dea0eba0e99eeac1a8509dda43ee111a922769775bc9d87e35ed465136a"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.91.tar.gz"
    source_sha256 = "35520d85c4cd9084fb7d373ae15fef4a4979015d9fd923f11143695bdbb352c2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.91-any-stack-50435dea.tgz"
    version = "0.0.91"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "bd96fe0155a890e87ed88d5b3669f4bc1a5560cfceb7fb7487f274a567537665"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "c9307e1ec5fcceab1cda86d4403f76df0ee174fd887826aa599db1442c23363b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.49-any-stack-bd96fe01.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "a6fbb399a5c9a378936773850faca1a1605488784ff0d0a56856bb99adfe2d3b"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "981ed625edb7013ae2a559be3b83c2df2bb1dd8d9d0aa20181f590d6ced99fd6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.92-any-stack-a6fbb399.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8fdefcc346f42484dda176bc1e26b9f7859fb7a440bcc72155c713fb27242762"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.100.tar.gz"
    source_sha256 = "4291959450971ccafda3d52f9249d0515449d3b6afbfa9c0904c97fef9fdd7f2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.100-any-stack-8fdefcc3.tgz"
    version = "0.0.100"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "b7d4a44fce40a81a55acabbeba0646b47c1b55f7d7674802d58eb8cfc45e4b2b"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "6801e684acbf300e8edb6d486f7a7c27d8cdaff9d6e144ceafc97e3db8a6b9e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.92-any-stack-b7d4a44f.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "f6ad213eca9144c4996a17e8db8e0d3e2d880483448180a5ff50a05d006646c8"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.19.tar.gz"
    source_sha256 = "2a80ed89b96d6066aeae4b4a239ade4c062fcf6cb62606062ce88b8127fc4951"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.19-any-stack-f6ad213e.tgz"
    version = "0.0.19"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "cda811ab0d193b8308222f3be281932d993631635b1b91f4cc7bcdf83ae35ef4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.126.tar.gz"
    source_sha256 = "1c5cd73f6463b1e5d5c8ffa5db975194471279c5a84c014e4eb901f72e461601"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.126-any-stack-cda811ab.tgz"
    version = "0.0.126"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.126"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.19"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.100"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.91"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.92"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.49"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.92"
