api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a7b3c594db8187168b76c73dca853c99b0ba9fddd1efc8a3f8fb76d38a85c9e1"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "aaba9353969f4be9a5b641107c36d7e6dc8e4673bc7fe551ea72b72c7f1b3555"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.93-any-stack-a7b3c594.tgz"
    version = "0.0.93"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d3229e4950bbdbd91503f7bb5b007b6e55f3a1d8ed1d79ba6602845ae0691961"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.52.tar.gz"
    source_sha256 = "61d9855004b60839411d1ec88f6db4ba30ca470033a7664f21158f5281f16975"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.52-any-stack-d3229e49.tgz"
    version = "0.0.52"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "6c0a8280ec9c7b200d8e9df9c388cdcf8286ef011fee0fb829636fed1d657ee7"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "4504d61b1312eeeed56fb00400a1526a0db1b409c276593118bee0d36591433d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.94-any-stack-6c0a8280.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8110a60401ffb7d115de88e028c5a764ef939cf4b365dc4251362ac2ef9b51ab"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "e59f423b4b51ef1eef6baddf4998f62eb06f06e152d4a928636e98d422c19a09"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.102-any-stack-8110a604.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "97b5c0b69ae1829342ea6ca3fdbe28fdd3c919329b46fd9140b292fcb38cf7b4"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "bc68ff0e3fb359fef8a6286366fe24ac8ccb660ecaeac1198c7508a33b7898a5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.96-any-stack-97b5c0b6.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "324976e96bff7373e9badf39919ba23df1454378b3575d76f88ca8afe0a4392c"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.21.tar.gz"
    source_sha256 = "f4282484c8c7efab7a43b7a7dc1ef8374566cfeae5e07fe910450b938d7da0af"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.21-any-stack-324976e9.tgz"
    version = "0.0.21"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "baf5bc98ce9789045e9f8865948eef24d1221099f1360988804dc5d6efe41bc5"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.130.tar.gz"
    source_sha256 = "b4e075ec5a2461c1f1a9bf23051220b5e68b5da6b7d55292fef4ded088b541ca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.130-any-stack-baf5bc98.tgz"
    version = "0.0.130"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.130"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.21"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.102"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.93"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.96"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.52"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.94"
