api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a8d2193acfa5d59707e348437ba0974312dcf5ec2ca675f30780cfd2b0dfcf5d"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "0b5aee17e388fed32ce934d93d9113773f59189326c27d668c5e78a1947f0f27"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.59-any-stack-a8d2193a.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "4f9c31e0a7887804bcc890c3ddee3f3f3a77706b4efb075b8c20057ad759383d"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "1635cb51bc975aaf097e938e790037360b9a8194642b0b0b5cde4324f45b3c14"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.63-any-stack-4f9c31e0.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "4f9c31e0a7887804bcc890c3ddee3f3f3a77706b4efb075b8c20057ad759383d"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "1635cb51bc975aaf097e938e790037360b9a8194642b0b0b5cde4324f45b3c14"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.63-any-stack-4f9c31e0.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d6907b288191140b499cacc9f8d0b67b2021bbbd6f9f63b93a447bfae0da01c1"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.24.tar.gz"
    source_sha256 = "41d094fa56fa554d31937a9858f66a91b224a79d157e035caebbaaefccb0b576"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.24-any-stack-d6907b28.tgz"
    version = "0.0.24"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "bfce0fe145a531f33d10e80eadd0f16abdf920c75b3364130a8858c7d7c212db"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.29.tar.gz"
    source_sha256 = "e1f8540a8741fb9f435142f5cf74b501d077761f3773c9dc19bf1386b8441179"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.29-any-stack-bfce0fe1.tgz"
    version = "0.0.29"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "bfce0fe145a531f33d10e80eadd0f16abdf920c75b3364130a8858c7d7c212db"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.29.tar.gz"
    source_sha256 = "e1f8540a8741fb9f435142f5cf74b501d077761f3773c9dc19bf1386b8441179"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.29-any-stack-bfce0fe1.tgz"
    version = "0.0.29"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "14ab1823e9baba1a4c2ca1e137fe5b2a262efe1448a67884b1c4cf42901e329e"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "4889ff2c347efcdd5c5d4f1da84569f2e8fa17eb207681f72c47907613329606"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.64-any-stack-14ab1823.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "a0a489bfb136c03ee4ce17cd4b9f63feed85121d51771456519d65ce19c90cb1"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "350d1a9b7030afa34e65ca880d8106c82636a53f4a821b96b43d2d160ffec495"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.72-any-stack-a0a489bf.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "a0a489bfb136c03ee4ce17cd4b9f63feed85121d51771456519d65ce19c90cb1"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "350d1a9b7030afa34e65ca880d8106c82636a53f4a821b96b43d2d160ffec495"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.72-any-stack-a0a489bf.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "09cbe1de1f7ece28b0f0f3b6bb01672386c8589781f430bf1edfae7515709cdf"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "e7d2073c5a0b33fbceb73d66b17210f9cbce8af0460f0af78c91967c2c5d1597"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.72-any-stack-09cbe1de.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8d45686afe4867d7f2d490fc937a85f515f00ec6ffff4d74f7b27323571b49d4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "0ecef56c36ce82bf07ca60ef7ede934ab5ca8c0895dbaf1eba9c78769850bd8f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.78-any-stack-8d45686a.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8d45686afe4867d7f2d490fc937a85f515f00ec6ffff4d74f7b27323571b49d4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "0ecef56c36ce82bf07ca60ef7ede934ab5ca8c0895dbaf1eba9c78769850bd8f"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.78-any-stack-8d45686a.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "d68abde46d36b024f577718bd93965153161285050e480c169b750194caa6833"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "0c1c9f2ec0bb324fd565b5d7015a5a412214c61c967b9ca057b6a834f93f1f1c"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.62-any-stack-d68abde4.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "358a3529783dfe47301e07260700f2178ab68e40816ca838c547dd0447392876"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "83bc8a716f264db5c4ed17e20e679850924d6b8ed6ae15bd166f56195a46bdb8"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.66-any-stack-358a3529.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "358a3529783dfe47301e07260700f2178ab68e40816ca838c547dd0447392876"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "83bc8a716f264db5c4ed17e20e679850924d6b8ed6ae15bd166f56195a46bdb8"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.66-any-stack-358a3529.tgz"
    version = "0.0.66"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.78"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.63"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.66"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.29"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.72"
