api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "9ead8e568789ad50bb64889b6c880375eaab469c63c081da97896423cd0dedcf"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "0bf6878cc5229c71dc9867d1ee61db5be961e8826555c87c2224631b16b618a4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.84-any-stack-9ead8e56.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2789e767b7f9311f82705ca501f53efc8e5e014e7d89306c053645e3f572c66d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.42.tar.gz"
    source_sha256 = "64870a19bc4de687f9fa7e33204476520c204e88a3892fa6e3eee11ad582415b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.42-any-stack-2789e767.tgz"
    version = "0.0.42"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "f0ca71a290724fd968d72cf71db9261a5c54d695a00b3eb73efebbbc566d3ba4"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "9b2c5ff871ceef8bfa4535babee44f470aa66463af994210bd1781f920b90645"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.86-any-stack-f0ca71a2.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "1606c64e70c64386ec714d423cd8ccca974bdcf98c01421153961292fce0f6ee"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "3cec6f82c3ff2b0b794bec070ba73f1f50d86a91c6ffde9d1995e57d06c5bb13"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.93-any-stack-1606c64e.tgz"
    version = "0.0.93"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "12bb27e88d8d527fc62b7c711d08023516ca8b678d125c7ca2ae09fb9c1f3963"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "6bb735b87b6237a9e7fa4100c3492b0e8344126eff3921a79a1b546a20f53c49"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.85-any-stack-12bb27e8.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "0ae2f426be6bc185e0aedff22643eac763aa2f5b970897d3d40a11b1a40e3cc7"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.11.tar.gz"
    source_sha256 = "da7b6c6d9fbbb4489d6abf51febe466a1347012524db0503bb564cd26003b2b6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.11-any-stack-0ae2f426.tgz"
    version = "0.0.11"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.11"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.93"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.85"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.42"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.86"
