api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "eabf1b8dc1776aa3db0b0c43f13a975809827380003e585fa2209e8a1ce310e5"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "4852fab497c95e6b0fa538a0f015f95a1833b54ca19601317b643b3ec1a52887"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.87-any-stack-eabf1b8d.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "942bd28404bdd0820f6a18a7a1a4bdb12e9870168b8e78c50384d8afe17c022f"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.45.tar.gz"
    source_sha256 = "25d5adbf5496077a8448f960c093b5716081e8e0e10ecfb08044e9a9037f05ce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.45-any-stack-942bd284.tgz"
    version = "0.0.45"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "25db8fd7c2c3f99d6e2706cf22fd3133b8697da374c7d7053bc18bc4ba3a955f"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "17a44874087329fb3e9bb68405ec06bd6ed1bd4910f2212db427370d861ea049"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.87-any-stack-25db8fd7.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "5f2c817ba77fc5e0ace813498e892c9ccc62713c12e1b9517e1373442473ec5b"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "a1631a31be801cc7e15356bf12f5297a96b87db00ff0080dfee21fb79e3af7be"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.96-any-stack-5f2c817b.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "c9c9c29406f0681ac6d9b4e512e5daec3403929c9050c6368f78261cb2d557bf"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "5c25e396f953b6efa2ee0574fed826582cff4aa75dab32f4df6487c083819697"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.88-any-stack-c9c9c294.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "6ee7d2773abec5cbff52c3b03551d5cf2d2f5ecc01ae7ee284fcf88407c37675"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.15.tar.gz"
    source_sha256 = "eac3a8401af38a9ff3ca71fe3ba7180dc12d233d2b135c4116a0d6ad83b91af2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.15-any-stack-6ee7d277.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "8c9c4019f16c40f8b39d5643aaeb61851fa79b3e4d5dda29f356f7d2072b0093"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.123.tar.gz"
    source_sha256 = "04c935c78969db64ef5ce861d46c941facc93af5a07cc783a41105111d00772f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.123-any-stack-8c9c4019.tgz"
    version = "0.0.123"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.123"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.15"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.96"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.87"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.88"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.45"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.87"
