api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "48040c39acc3be5a004c1bc19e0138595f393f5f6ee96b994074275910b12b8b"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "76841c511c6c21a562d246008c519fd6369324c0d2f9785c2abd125fce74a8e1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.92-any-stack-48040c39.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "a63212d883c511228ccb661ae76fb6e8aede932f226df39570c96772c26b7e42"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.50.tar.gz"
    source_sha256 = "35982ae6b4236c41c683db42e7a0174f370b4dc1bdf1d28e78cd5a16ad42260b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.50-any-stack-a63212d8.tgz"
    version = "0.0.50"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "6c0a8280ec9c7b200d8e9df9c388cdcf8286ef011fee0fb829636fed1d657ee7"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "4504d61b1312eeeed56fb00400a1526a0db1b409c276593118bee0d36591433d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.94-any-stack-6c0a8280.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8110a60401ffb7d115de88e028c5a764ef939cf4b365dc4251362ac2ef9b51ab"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "e59f423b4b51ef1eef6baddf4998f62eb06f06e152d4a928636e98d422c19a09"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.102-any-stack-8110a604.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "011f78a94dd34c253000085ffbcbf295c08edce56229d436da4c9cfe0e7781a3"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "86a719c14caa161405258b40ad34de3cebb031c49c809b6e1e4c471b1d40c314"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.95-any-stack-011f78a9.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "324976e96bff7373e9badf39919ba23df1454378b3575d76f88ca8afe0a4392c"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.21.tar.gz"
    source_sha256 = "f4282484c8c7efab7a43b7a7dc1ef8374566cfeae5e07fe910450b938d7da0af"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.21-any-stack-324976e9.tgz"
    version = "0.0.21"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "986157669040a56bd29e951a48dae95d712aca9a8fb24244d1875c63a2f9037d"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.128.tar.gz"
    source_sha256 = "41daf54f94d02ad529fdea23f962f7096f917853f8be7af49248fdd5a460710a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.128-any-stack-98615766.tgz"
    version = "0.0.128"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.128"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.21"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.102"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.92"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.95"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.50"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.94"
