api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "d0a36f52d30bc2c49b7b211b49361b4213b5ed63e518f2aecfecc5c6fbb49934"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.43.tar.gz"
source_sha256 = "537379d52e26bd8e83f5e1e613a2aff3979d78e2870a3738d763c4ca42ac9d1a"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.43-any-stack-d0a36f52.tgz"
version = "0.0.43"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "0ad0af866a38eff1dfc4e8dfc18e9855f406ac2b14b4e3d010c63b33b0f28cb7"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.10.tar.gz"
source_sha256 = "22fbad9c03d12f4a9dba1c2d52d5cb1dd9c4d99f000a18a25c6033a33bda6433"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.10-any-stack-0ad0af86.tgz"
version = "0.0.10"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "bf43894d63c20912f8b19e4fb423d731004346ea262a45f70aee06acefbcfb56"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "3a25defe9484aabe08fdf224379593ad494c56e28e6b707460e9223d0578b29d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.47-any-stack-bf43894d.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "df5d7ac6dbb867b54e94212cca34b9cd96807dfa18b054c74366023543962173"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "bd07fc5020ab81faea5f135b1bd1213e1e4b0c4d4578995c301e167c02d00f4b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.56-any-stack-df5d7ac6.tgz"
version = "0.0.56"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "9c2921ca5c15fd6364389b273e4e2fe82f20a525ac2333cb6ed1f2742384828a"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.48.tar.gz"
source_sha256 = "c212930c0191389e11c96c09cae69421479aa46033f9cdf8dcf1761e6f61cb11"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.48-any-stack-9c2921ca.tgz"
version = "0.0.48"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.56"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.43"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.48"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.10"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.47"
