api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "81d46b248cbaf15cbd85f3cc7c04d003a0de0d36dd00ad028dff5f52156ed563"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "f443a01a15bb4a1a79e2924688b93406a5f3258f98f87b5d4a5ad71c40b8f7f8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.115-any-stack-81d46b24.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "947d50aae187737ab51e8dc7177edf12b7a26a4aa19ed7bf3f2587698e37ecc8"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "c3ab00efce75817c90d1ddbba7beb1c60c9e68f9fdb5a7191d9bd1a9d6971c14"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.67-any-stack-947d50aa.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "86087d8b70605595f51cf105e0b091742dda6e0f68b4033bc3d51c60e3734500"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.113.tar.gz"
    source_sha256 = "b8187d636e9229262bcb37d5517d263111a7bc146a2ca4834fff4c539d079fdd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.113-any-stack-86087d8b.tgz"
    version = "0.0.113"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "a795b9b21662250a7534e44f5bd9d77bf328bae045b2682c3e841577e4615e1f"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.125.tar.gz"
    source_sha256 = "af2d1c8ffd982fd09a7d8f5a7e0398c00e4466b9cda083cc0d04f61a218f7724"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.125-any-stack-a795b9b2.tgz"
    version = "0.0.125"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "496f5767f89541b1d7013abbd4eeb7ba8f8d29d2656c761fd05d78691b0ec514"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.119.tar.gz"
    source_sha256 = "a2e104538235312cb9b417b5f5c26cfe96f63d5c95bd7d16e7f257bb867e2863"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.119-any-stack-496f5767.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "6a71321d1d096ffec72acdc707932b3e3364fbbadea45741513db94bab82be71"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.43.tar.gz"
    source_sha256 = "8a3ab36445d674c108d155262666b1dd9efa084a1dd9b1b98a8c3898a0e531f6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.43-any-stack-6a71321d.tgz"
    version = "0.0.43"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f53300cd8b742bb08235a9f8ad4cd23aa7738cf4dc50be5810d9a49177782b1a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.155.tar.gz"
    source_sha256 = "38870fec85e70e7e5bfb25a2a4bb89e80678ded3b0e27ee5be332a33dc8a681a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.155-any-stack-f53300cd.tgz"
    version = "0.0.155"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.155"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.43"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.125"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.115"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.119"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.67"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.113"
