api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "c14304a5facb93212647957eb59a4e2941e0a4b35980127e3f8637800cff2224"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "f7df8325f824224c6dc96430d3878622f4da95cfddb1daf5131819791fe874b7"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.55-any-stack-c14304a5.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "7165d8c190734b63b354e03a234aecf97b4a006df56decbccecb58fdd73353ef"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.20.tar.gz"
source_sha256 = "790d2874e696b8276171f6bf6836412c944a436d3f81b21434184e9bd0bc476e"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.20-any-stack-7165d8c1.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "edab458ca31645e27d5b372ea45a3c1de4858914b3b40f8e4f4980a1c7c7ce4c"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.59.tar.gz"
source_sha256 = "8d242ba28e99b33d11ca0e1150e687da33dda16094c9f80595798f0791020086"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.59-any-stack-edab458c.tgz"
version = "0.0.59"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "a3729f707e31010832421386834ee8fd0f95afb82896f6507f2997ee8a47fc2a"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.68.tar.gz"
source_sha256 = "f0261ee79bb29fb8681c0f932b9947ad6273d780f5ff8ecb0d29787820a73c2f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.68-any-stack-a3729f70.tgz"
version = "0.0.68"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "3e5f4129183fb359cb8ce33a92d93cabdea1603024c57bee4092482f88011c95"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.58.tar.gz"
source_sha256 = "c23a468b484cd3deca45c70d3a2ac98fdeee9dac619ca907e04aeff859baa306"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.58-any-stack-3e5f4129.tgz"
version = "0.0.58"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.68"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.55"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.58"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.20"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.59"
