api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "484ff65dcc2813bf9787683419e6cda301d6575884a72eeb0188c3f7795dab32"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "220b83b4320bd4ccb3d0d227726155e68bdc48f26109a1449295b150fb8d84ca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.86-any-stack-484ff65d.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "942bd28404bdd0820f6a18a7a1a4bdb12e9870168b8e78c50384d8afe17c022f"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.45.tar.gz"
    source_sha256 = "25d5adbf5496077a8448f960c093b5716081e8e0e10ecfb08044e9a9037f05ce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.45-any-stack-942bd284.tgz"
    version = "0.0.45"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "25db8fd7c2c3f99d6e2706cf22fd3133b8697da374c7d7053bc18bc4ba3a955f"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "17a44874087329fb3e9bb68405ec06bd6ed1bd4910f2212db427370d861ea049"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.87-any-stack-25db8fd7.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "7e2e1d0f8f646371e9a1621f4b241b1ec37899f566d34705adb0eec247a01404"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.95.tar.gz"
    source_sha256 = "cb6467c96524558fc654d9e2c64307a67d759056d6023fb4a4a9c667bc7d7dc1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.95-any-stack-7e2e1d0f.tgz"
    version = "0.0.95"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "c9c9c29406f0681ac6d9b4e512e5daec3403929c9050c6368f78261cb2d557bf"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "5c25e396f953b6efa2ee0574fed826582cff4aa75dab32f4df6487c083819697"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.88-any-stack-c9c9c294.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "97721d30a854253faa853df732777035c0e576462bfacfdadafe539c2006900b"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.13.tar.gz"
    source_sha256 = "1800d89c65c2b2fa3213722d2e25b079611ac09be439aceafc8596eae7db25e4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.13-any-stack-97721d30.tgz"
    version = "0.0.13"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "de1507433f0e16e9ac0d2738c89d8823d5283a6d76690cac7f4eb7d529704cb0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.122.tar.gz"
    source_sha256 = "bfc6769aca3c88c1c66e7493c16245a1fe96c51d90203406c95a14d02c18b926"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.122-any-stack-de150743.tgz"
    version = "0.0.122"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.122"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.13"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.95"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.86"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.88"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.45"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.87"
