api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "2c5006bd57f1546bb8e5de9a99b93a2b4c7c206d9a350f9eb8579534f36a0ad1"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.98.tar.gz"
    source_sha256 = "0dea002061a7f75330e6842fe96f1d3f12c5a1d14c15952251b0b9ff86fd9528"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.98-any-stack-2c5006bd.tgz"
    version = "0.0.98"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "fb36739711b25840e4c45897402c491d812fab801ba5e4c9279eb9dccebbc2e2"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "e948c8c2012a977d031139ae7c942c17403676abda3a34582915ac29afaf604b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.56-any-stack-fb367397.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "ddbb75c38539e8264f7692cd509c57cb3d56c557fe31ce6e37dc264292189332"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "6c6d5a6b2e5d713aa06b5e41947bd4ff8fc558b4fde07dda9117a23b3ab8e30a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.99-any-stack-ddbb75c3.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "b404708c5d38221abf1e54be6430f01028c21a664d958ce2666e5d92b5219a1f"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "76025eda7e5c82b37bb42cc51453df1998b5b3c390e372049bf729e2866ccb8e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.107-any-stack-b404708c.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "0951e2bac9149f5c26829bc4a00a84c4ddf0395a2894b317cbe7c0dd17b31e65"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "1d8454ee546a12dedef805510a9f0d4584a6cb98f1dbd5c3573a9f9824d3b00a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.99-any-stack-0951e2ba.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "9d9e7ea1bea240d0f9038a70ccd7c3ca4d9936d2e53d9e524c387902548fd859"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.26.tar.gz"
    source_sha256 = "b5d079dd9d37b6cb5f60849b45128ca88498b4284e5bdf5dc248dabe0db3cd48"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.26-any-stack-9d9e7ea1.tgz"
    version = "0.0.26"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "541c4fc22a11b9adb85248e7120c31f7e906dfbe22c432501c4b1d8a79d3300c"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.134.tar.gz"
    source_sha256 = "ad9f7f7de788a4b2cb6665a226740ebe97d39b4b100aed7a3397bfff197d7654"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.134-any-stack-541c4fc2.tgz"
    version = "0.0.134"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.134"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.26"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.107"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.98"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.99"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.56"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.99"
