api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a8d2193acfa5d59707e348437ba0974312dcf5ec2ca675f30780cfd2b0dfcf5d"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "0b5aee17e388fed32ce934d93d9113773f59189326c27d668c5e78a1947f0f27"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.59-any-stack-a8d2193a.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "b271db93b3a0fca5221d9373dcc5c1b05e1b408db76495a193dd97532d122644"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "628db342045a0cdd1d9ad609dda82eaaac45ad123d73e9b188ad1496ced26575"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.68-any-stack-b271db93.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "b271db93b3a0fca5221d9373dcc5c1b05e1b408db76495a193dd97532d122644"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "628db342045a0cdd1d9ad609dda82eaaac45ad123d73e9b188ad1496ced26575"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.68-any-stack-b271db93.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d6907b288191140b499cacc9f8d0b67b2021bbbd6f9f63b93a447bfae0da01c1"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.24.tar.gz"
    source_sha256 = "41d094fa56fa554d31937a9858f66a91b224a79d157e035caebbaaefccb0b576"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.24-any-stack-d6907b28.tgz"
    version = "0.0.24"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "e446dcf648afd2a7c31e2dfe23572f512097d45c41423cb0fe01a51f0a995182"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.34.tar.gz"
    source_sha256 = "a9863af74a6509c33f706f6dec89b60077dffd138361013e6550d49ebda7ffc2"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.34-any-stack-e446dcf6.tgz"
    version = "0.0.34"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "e446dcf648afd2a7c31e2dfe23572f512097d45c41423cb0fe01a51f0a995182"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.34.tar.gz"
    source_sha256 = "a9863af74a6509c33f706f6dec89b60077dffd138361013e6550d49ebda7ffc2"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.34-any-stack-e446dcf6.tgz"
    version = "0.0.34"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "14ab1823e9baba1a4c2ca1e137fe5b2a262efe1448a67884b1c4cf42901e329e"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "4889ff2c347efcdd5c5d4f1da84569f2e8fa17eb207681f72c47907613329606"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.64-any-stack-14ab1823.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "cc63f140ac1ed90ccd9c006a3a577e39e8dedcbeec42171e28048e7fe768946c"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "a6a7b27c16540f5c1624974e4d6784c986fd007eaaf1112c151d64d3afaf1345"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.74-any-stack-cc63f140.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "cc63f140ac1ed90ccd9c006a3a577e39e8dedcbeec42171e28048e7fe768946c"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "a6a7b27c16540f5c1624974e4d6784c986fd007eaaf1112c151d64d3afaf1345"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.74-any-stack-cc63f140.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "09cbe1de1f7ece28b0f0f3b6bb01672386c8589781f430bf1edfae7515709cdf"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "e7d2073c5a0b33fbceb73d66b17210f9cbce8af0460f0af78c91967c2c5d1597"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.72-any-stack-09cbe1de.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "50404229d8eb5817f7fb1deef51e7660f04a396d7f7dd6d836d60859807e6fe4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "1d8d6a29272d8e1a12aa294e302549404cca28886352108c0ddd1513d9551171"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.79-any-stack-50404229.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "50404229d8eb5817f7fb1deef51e7660f04a396d7f7dd6d836d60859807e6fe4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "1d8d6a29272d8e1a12aa294e302549404cca28886352108c0ddd1513d9551171"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.79-any-stack-50404229.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "d68abde46d36b024f577718bd93965153161285050e480c169b750194caa6833"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "0c1c9f2ec0bb324fd565b5d7015a5a412214c61c967b9ca057b6a834f93f1f1c"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.62-any-stack-d68abde4.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "29a1fd73da8cf7f30608bf2df069bb4ce2015dd5a0be7292e28205265ccb652a"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "8c26bf749893c0021ca817d1cdd846676b5fdc90de467343cc861763c04bd29a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.69-any-stack-29a1fd73.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "29a1fd73da8cf7f30608bf2df069bb4ce2015dd5a0be7292e28205265ccb652a"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "8c26bf749893c0021ca817d1cdd846676b5fdc90de467343cc861763c04bd29a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.69-any-stack-29a1fd73.tgz"
    version = "0.0.69"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.69"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.34"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.74"
