api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "bfbfbb8471491dde3c69731abdc916e056f6db100709969da60dea96ed2fbfc0"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "0c5c8f24a6cb37a3c3d70a0b2b341952480355d1367980666bd5b9ac19c40f90"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.41-any-stack-bfbfbb84.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "faeee08db9d5cb5cfe2a41ec2a8a89c9fcf00b72548012fc4615912f28517f32"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.7.tar.gz"
source_sha256 = "68b699790e5207ddc208dce036761894a786d826a0761eca05e189333c77378d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.7-any-stack-faeee08d.tgz"
version = "0.0.7"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "7ed34e677152936daf8fcbae08074646e4d1b5bf1b25ba8894812b78235d8ab9"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "fd4276919853ff89dd731211f74760a8a63cab9e19b4aa5f2a2aa9d520bca571"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.45-any-stack-7ed34e67.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "5c29729d52d58c840934265db2fe610e0e3ecdc9c12757f50c66c9043fc8bae8"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "4abce4f8437bf7cff755c91ccf6c24238da8c8aed8e1034366d7d91fc27b72fa"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.55-any-stack-5c29729d.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "de80860736f7d1727d301b05463a35e6a5a54ef502655432d476506b075324e5"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "60b0c8ad47915831257aeeb11840afa4e46098aec9826d12a55161658e36ff5f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.45-any-stack-de808607.tgz"
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.55"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.41"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.45"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.7"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.45"
