api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "1899534654f48ac86f336929266975896c06a1ce9febdd1cfe9818662b369e81"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "5652f71c37884c77d8c025f77fac0b0427cb4cd17643b5c0fd83cb369a038b99"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.104-any-stack-18995346.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "730ec02fdbffcbe538150b6df1219ea343dc8ec7203d0426c6f2384b86bfe79d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "9e58c2142a839dfa59addcca36708f9e8b4073e3801ac80252c745ea7ce41342"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.58-any-stack-730ec02f.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "4a7d88dcb736bc9c4a6b90aa88451c1243071e9e5e839c5b0eb7669a84670b44"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "c66bb5e53a680474de724386db8e992d9047317dcd8ac74f11c8a368de68a0ca"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.103-any-stack-4a7d88dc.tgz"
    version = "0.0.103"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "983ea4909a5df3074e2799587100e27c26dcd3f3c594d8d1d1a97c445f126b65"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "7c3b03ce76a721c7b6a234daee06b0b0b44ec0100467f7d2c04f9508a096eff8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.115-any-stack-983ea490.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "dcea1ee35bb34b89c9a4ddf8b782ed963466859602f1e71f594f5fbc029a8784"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "e7046d6ffd0ff9d98f19bda0176cca533548ef8c7f0800ddc36b7be5b3035fda"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.110-any-stack-dcea1ee3.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "325d6ee2329b6c856eaafdad07821a1e8987ebc508df476988e14bc7fb4ca4d5"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.31.tar.gz"
    source_sha256 = "e5d6a9bda355055795ef2f4d6f817b560be736e4abfa3cae176ed025997801f7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.31-any-stack-325d6ee2.tgz"
    version = "0.0.31"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.31"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.115"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.104"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.110"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.58"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.103"
