api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "e3a66c1847f3de0eb0f8e0d7ed8d5a53925498d7f8d3bbce0492a13fc121990c"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "c7a24a465b1ae9ae8b5623f690084c295013fd9672c1dc8314b7d8f0bfd37550"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.94-any-stack-e3a66c18.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d3229e4950bbdbd91503f7bb5b007b6e55f3a1d8ed1d79ba6602845ae0691961"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.52.tar.gz"
    source_sha256 = "61d9855004b60839411d1ec88f6db4ba30ca470033a7664f21158f5281f16975"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.52-any-stack-d3229e49.tgz"
    version = "0.0.52"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "6deb8eecd202edf3ee30fbb8604b823f9e68d14fc28664e4c6e69eec7418413d"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "41356f3854d1d82e8a4362ae751aa6ebb012e50bb006dac8abf1386738a16b1f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.96-any-stack-6deb8eec.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "5a5065a57634b954f5a1bf04d7fef94d4cc0cfb501e8e430996108577f6211ff"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "13660c57b6f0c42745ccca05c45caa286268c7b290ff860dd5b09870aef6d142"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.103-any-stack-5a5065a5.tgz"
    version = "0.0.103"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "97b5c0b69ae1829342ea6ca3fdbe28fdd3c919329b46fd9140b292fcb38cf7b4"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "bc68ff0e3fb359fef8a6286366fe24ac8ccb660ecaeac1198c7508a33b7898a5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.96-any-stack-97b5c0b6.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "7b30ce1c950353782f5b92ff972b9e6c62d91a2962f59f274f5dd08da84a0340"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.22.tar.gz"
    source_sha256 = "08c092f0ef3ae9de16ecc10390fa0b02a2cb0871d2500c252f6a2806599a4094"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.22-any-stack-7b30ce1c.tgz"
    version = "0.0.22"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "00e0e332828ca0f780fe62a3f29bd4e8854672135d55bf06075df97706bf0a73"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.131.tar.gz"
    source_sha256 = "b6150bcb6213b85a8d89491f5d516db568ca6afa21a2506116f77f9cf0780b75"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.131-any-stack-00e0e332.tgz"
    version = "0.0.131"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.131"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.22"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.103"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.94"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.96"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.52"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.96"
