api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "442d1b1fdc820023ab77c3254f5a15280ebf1b769d5080b0124e7859a604c7c7"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "a0e7f01a53e14cef56e70ef3a95b028fcab3f98c7b2c5944c0081afe32aa8128"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.80-any-stack-442d1b1f.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2789e767b7f9311f82705ca501f53efc8e5e014e7d89306c053645e3f572c66d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.42.tar.gz"
    source_sha256 = "64870a19bc4de687f9fa7e33204476520c204e88a3892fa6e3eee11ad582415b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.42-any-stack-2789e767.tgz"
    version = "0.0.42"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "d9fa56354af3246af6185a09c79536522b39187e3252c4c1c85d21f0b069fe13"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "7ee092e9a4bc97dbbbbff069da41551589b6eb50cc5b3d0f7a87a8f6b71629e0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.83-any-stack-d9fa5635.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "cd61ff7bc7b7fb69cd5d2af674dbfcaf23009a291d298b945a48ba8b661e04c8"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "bf52b52e3b88edcd02a18e11a3db133d2d891bb44d59b5bb0d575bc452618add"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.89-any-stack-cd61ff7b.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "46aade15bd849e65e3e48aef5efb3fe30acb5eba8e05581c21869e50dcdaa892"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "0d2d3311e3bd369026734b6a72a1347e4cae541e706c2e7c6db266906e0e8384"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.78-any-stack-46aade15.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "963b6d98ead85f5e32fb3b66f74143cc106db6a5ec238eddf53e6ec8a1f69279"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.9.tar.gz"
    source_sha256 = "bee58760d864d63e3387e6675607e0196b044937107d3f578f09aa059d5be695"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.9-any-stack-963b6d98.tgz"
    version = "0.0.9"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.89"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.80"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.78"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.42"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.83"
