api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "c08a5618dcca044cffe14e2ca07a5ab495f7f0faddbf07601db9f194429e38b4"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.127.tar.gz"
    source_sha256 = "c0068ccb62d786d06c350d363cb71a75eba366e923891a09718651b63faa4027"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet_0.0.127_linux_noarch_any-stack_c08a5618.tgz"
    version = "0.0.127"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "187689dd6b5b47e3e89e8d4141a54f546b781c4015aab6cc5776e8667a7e739d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "e3438c906498a3587a03f93d60d32914c221aa89e91d3d6f5f6d34277637f683"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build_0.0.69_linux_noarch_any-stack_187689dd.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "0ec017ae0096fedd637605e3b637c4c9492872e9e8928fa7f4d782239e044872"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.120.tar.gz"
    source_sha256 = "7a487b95a586914001e19c548f5992b214f8014eb1a0bf239c5abe930be5c18d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf_0.0.120_linux_noarch_any-stack_0ec017ae.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "495a474d37bc44a23a2e642bb8fb5f0baef56c735a08356beec1475fba123c0c"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.133.tar.gz"
    source_sha256 = "e5161146f310e46d1e37baaefbc47a4b1139e0e139f5704ed3534f8ec3116d79"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime_0.0.133_linux_noarch_any-stack_495a474d.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "94c8f3074e13a2bf4c28d1add8d7cc650d9253c62527384f665d92f1c41380b8"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.131.tar.gz"
    source_sha256 = "92b09e5858b51080a2df82723bb1444c95933b27778c7b3274078e585524dbf0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk_0.0.131_linux_noarch_any-stack_94c8f307.tgz"
    version = "0.0.131"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/icu"
    sha256 = "8362a7254ce3ead513935dd2732db5a55f770df9e36ce95136accf047ed4e938"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "4261315fb9849df01bace33869e75c13fc1deda89894e25bd839c73720039645"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu_0.0.51_linux_noarch_any-stack_8362a725.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/node-engine"
    sha256 = "fe616060aee70ccd5f7cfa83aca7f0adf5a55d6eae9599f317163fe90ed5ace0"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.177.tar.gz"
    source_sha256 = "0f1f93c7922cc25e0f1deffc0978b8e18d82cb390eb6adb63da6c1c6ad8a21cc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.177_linux_noarch_any-stack_fe616060.tgz"
    version = "0.0.177"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/node-engine"
    version = "0.0.177"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/icu"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.133"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.127"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.131"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.69"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.120"
