api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "0fee3faff4ee41f8a44d9bce1e8858c089c40dc324c66fb952d5139a757d2e17"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "8a5e657f66894feb4195f6da56852c5db3030b1daf3884653722ac2d64b939da"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.72-any-stack-0fee3faf.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "dae493552e0ec4bb7487f8105f2227dd0f96a6a03f64a17a55c0aa0ba0e2a10d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.36.tar.gz"
    source_sha256 = "5067888e4a253e2f91e037aabd42228891b765d2fc27cb8e865a3642582f3ae3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.36-any-stack-dae49355.tgz"
    version = "0.0.36"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "c18ee2a716e72c7358dce6bf212c34f606f62ad7979c1bd24ad9766e6677e2fe"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "cd01dbd5898ff2f50dc425c60b1d5130f2ba07681e3950140da36571049c0742"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.79-any-stack-c18ee2a7.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "db17611dee3261f26a54752921df5e3f7b08aa54d32c2429c36af81f246e8d75"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "39b2a5fd6bce5ca41dcff1febb3d35921c49dc28e09405378743fce7373df2e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.82-any-stack-db17611d.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "752ab05def8d36617cb94cea41a51f02bffdd9ea433495743daaec3865c37948"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "0ba29ea8e702cec3e314ef086d5e4ca22b5ea205346951477321cd47b93ccb9c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.71-any-stack-752ab05d.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "a313800accf3a9ac271e77d43882b7f73defdc200fdfc327fd99e428b8a45c91"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.6.tar.gz"
    source_sha256 = "78291fd001552420efae73ff6691e67ccff2bcc7bcf0208e01fbac83f29108e3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.6-any-stack-a313800a.tgz"
    version = "0.0.6"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu-cnb"
    version = "0.0.6"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.82"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.72"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.71"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.36"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.79"
