api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "8ba86d906e74f8d92363741f1855f65308725db71c350e08409ba90f8c6dcf74"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "183b72898cb685e56b5691f5c7a9a07b0dae9ead64b881d4137d02f8bd78cb0f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.71-any-stack-8ba86d90.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "4188801721e67d7e0e59da8e7b1e4fd23f390c812d73be07291b3bf54b283e3d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.35.tar.gz"
    source_sha256 = "13740a1165c750522b05bba79d10f91ae191aa3a1c38d448477b7a9859c8a852"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.35-any-stack-41888017.tgz"
    version = "0.0.35"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "3a1b5fb9e4221ebd1cbbce269b68b42f33d795313d22d41ce62493e26726bc8d"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "175455445cde62866116e0f877e287c55004bfdbfe386cf2d2d07a6a2598220e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.77-any-stack-3a1b5fb9.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "414fe7b2d24258e98f8212dd94ea2001729c75747f7f61b9356bc4a4cca50236"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "3939b1ccc0ed703ebe8a7e37b55771167c611e48608d7b3cc44a4a15518dee82"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.80-any-stack-414fe7b2.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "2f2d89f6aa23b3298d1eac9ff31f65d17edf2573b155ccdec5aa266a8804898c"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "da1f4ae4a9477050eadaa1b81f954f19aa3b454bd266295e0179803477d13524"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.70-any-stack-2f2d89f6.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "7c333716c05727fd40a29cca7576cd1ada9cb7f852db61a4e9bb2990117c6c00"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.4.tar.gz"
    source_sha256 = "c36af401b5df72c5b8fafcb3cab22baddf599b63247a06fa3423027b2a3ea812"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.4-any-stack-7c333716.tgz"
    version = "0.0.4"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.80"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.71"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.70"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.35"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.77"
f8212dd94ea2001729c75747f7f61b9356bc4a4cca50236"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "3939b1ccc0ed703ebe8a7e37b55771167c611e48608d7b3cc44a4a15518dee82"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.80-any-stack-414fe7b2.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "2f2d89f6aa23b3298d1eac9ff31f65d17edf2573b155ccdec5aa266a8804898c"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "da1f4ae4a9477050eadaa1b81f954f19aa3b454bd266295e0179803477d13524"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.70-any-stack-2f2d89f6.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "2f2d89f6aa23b3298d1eac9ff31f65d17edf2573b155ccdec5aa266a8804898c"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "da1f4ae4a9477050eadaa1b81f954f19aa3b454bd266295e0179803477d13524"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.70-any-stack-2f2d89f6.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "b8c5140883311a72c186de47b04256ed2235c75937cf7aa0e10544fe01b6b6f1"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.3.tar.gz"
    source_sha256 = "4214738eb2297ac7d3d133ad319d95f48608d47d17c9d09d522df80abbb5fde0"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.3-any-stack-b8c51408.tgz"
    version = "0.0.3"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "b8c5140883311a72c186de47b04256ed2235c75937cf7aa0e10544fe01b6b6f1"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.3.tar.gz"
    source_sha256 = "4214738eb2297ac7d3d133ad319d95f48608d47d17c9d09d522df80abbb5fde0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.3-any-stack-b8c51408.tgz"
    version = "0.0.3"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    optional = true
    version = "0.0.80"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    optional = true
    version = "0.0.71"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    optional = true
    version = "0.0.70"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    optional = true
    version = "0.0.35"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.77"
