api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "c4ab47c86acf80a4748285fcc2d9b353ea0814a31182ac498dd1b07b31f40f98"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "feb84e8e32cbea9084ebb2eda4b768324e4f0e54dfca35d70304cbcca79222b0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.88-any-stack-c4ab47c8.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "942bd28404bdd0820f6a18a7a1a4bdb12e9870168b8e78c50384d8afe17c022f"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.45.tar.gz"
    source_sha256 = "25d5adbf5496077a8448f960c093b5716081e8e0e10ecfb08044e9a9037f05ce"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.45-any-stack-942bd284.tgz"
    version = "0.0.45"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "fa28a3795ba0f4f541584055488ccd98c0d70b2bd8bf48cf862d3e46929f8784"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "8281a7c7b88d5ce44f1b2c0b19c0066ddb2796b40dee4dc8f93c7921daf37264"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.88-any-stack-fa28a379.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "80bd48f7b843418576c920da6f1a8a8b72304cd1c574d120a70af459a9d9cba9"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "73ea9a892b23961c6dbe176d33db8f5132926d965fabe3aceb158c4c229205f1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.97-any-stack-80bd48f7.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "c9c9c29406f0681ac6d9b4e512e5daec3403929c9050c6368f78261cb2d557bf"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "5c25e396f953b6efa2ee0574fed826582cff4aa75dab32f4df6487c083819697"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.88-any-stack-c9c9c294.tgz"
    version = "0.0.88"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "6ee7d2773abec5cbff52c3b03551d5cf2d2f5ecc01ae7ee284fcf88407c37675"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.15.tar.gz"
    source_sha256 = "eac3a8401af38a9ff3ca71fe3ba7180dc12d233d2b135c4116a0d6ad83b91af2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.15-any-stack-6ee7d277.tgz"
    version = "0.0.15"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "3d6886e002d41471d723d98a61da443e53ed71ad93496831973675c2bb8d12a4"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.124.tar.gz"
    source_sha256 = "981572423aefa077a8bb127b6a6d3fd322d5ad1e4ea0cfaba38b61095235c8f3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.124-any-stack-3d6886e0.tgz"
    version = "0.0.124"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.124"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.15"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.88"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.88"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.45"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.88"
