api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "3b1586fc2141f3409949c64a0ecfd65bc409234b29233bde48d2e9152486574c"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "48ca6ef8d47312ad7d7ec16b5eeeb06cb7b98b600f42ef6b95c664a5efd24f9e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.75-any-stack-3b1586fc.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "fdf5b23a52dfc9017f586ee4a79d8534809841ab4e0c10021299a207c27e94ee"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.38.tar.gz"
    source_sha256 = "0af21df39d38b4a695f12c18dd0de8f8b6176016af32531645c1425902dbbdc3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.38-any-stack-fdf5b23a.tgz"
    version = "0.0.38"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "2f7e31a45b0fd76eac6fcfc6db74527aba59804071bed162aad330f41a5b6742"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "a5b2af5099ccb0590090b8c8d4b33d9c2da218bc7c938d61fccde3649fe616f6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.81-any-stack-2f7e31a4.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "996045fba8be03bcfbd368bd96c4c088ca63bed1370993062dda5aa7ba16be99"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "369078b3e559eef852f940c32276f98606678a53078d5fd4e742035dc6b0d4b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.85-any-stack-996045fb.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "a82dab1b5c9aaba87f86bf6a294c7ff9708ec00f08ffc66c2070df1a82936efa"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "91a4ba9d3bf594b07c90f91010272916a67035f925497dba3aa51cc04d38a6a4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.74-any-stack-a82dab1b.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "963b6d98ead85f5e32fb3b66f74143cc106db6a5ec238eddf53e6ec8a1f69279"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.9.tar.gz"
    source_sha256 = "bee58760d864d63e3387e6675607e0196b044937107d3f578f09aa059d5be695"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.9-any-stack-963b6d98.tgz"
    version = "0.0.9"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.9"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.85"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.75"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.74"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.38"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.81"
