api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "bfbfbb8471491dde3c69731abdc916e056f6db100709969da60dea96ed2fbfc0"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.41.tar.gz"
source_sha256 = "0c5c8f24a6cb37a3c3d70a0b2b341952480355d1367980666bd5b9ac19c40f90"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.41-any-stack-bfbfbb84.tgz"
version = "0.0.41"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "7ed34e677152936daf8fcbae08074646e4d1b5bf1b25ba8894812b78235d8ab9"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "fd4276919853ff89dd731211f74760a8a63cab9e19b4aa5f2a2aa9d520bca571"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.45-any-stack-7ed34e67.tgz"
version = "0.0.45"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "33a681f644795a10d5559186613357e56cd5a09660633d55062ff4622ccf06e4"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "1f6a1e796d0dbb10b8c87021562bbfbf698faa84a9da21b5586920ad6a387eb2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.54-any-stack-33a681f6.tgz"
version = "0.0.54"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "de80860736f7d1727d301b05463a35e6a5a54ef502655432d476506b075324e5"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.45.tar.gz"
source_sha256 = "60b0c8ad47915831257aeeb11840afa4e46098aec9826d12a55161658e36ff5f"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.45-any-stack-de808607.tgz"
version = "0.0.45"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.54"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.41"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.45"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.45"
