api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "96c46f244c47cffb0da49bc368d2c08d2078aa88b9d37b82f54f8728bdff49b8"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "fd3ff870e53e85b69060c30a0415137f202e27a04bef4bf571759d1c86b1e822"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.97-any-stack-96c46f24.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "1e30185675257839e73df3adb6bab28e9f59390be94a83277800bac61db57cad"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "763bd2418f71ff8f71466ff8fd240dd58c237123f57386b2c35114d214ee9b5a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.55-any-stack-1e301856.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "ddbb75c38539e8264f7692cd509c57cb3d56c557fe31ce6e37dc264292189332"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "6c6d5a6b2e5d713aa06b5e41947bd4ff8fc558b4fde07dda9117a23b3ab8e30a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.99-any-stack-ddbb75c3.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "b404708c5d38221abf1e54be6430f01028c21a664d958ce2666e5d92b5219a1f"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "76025eda7e5c82b37bb42cc51453df1998b5b3c390e372049bf729e2866ccb8e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.107-any-stack-b404708c.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "0951e2bac9149f5c26829bc4a00a84c4ddf0395a2894b317cbe7c0dd17b31e65"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "1d8454ee546a12dedef805510a9f0d4584a6cb98f1dbd5c3573a9f9824d3b00a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.99-any-stack-0951e2ba.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "14c24db559fd834e01b244546fba9a65fb36c165004c1a9063eb2ec3bd84728b"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.25.tar.gz"
    source_sha256 = "cca3bf86c6d3d361a18d500ce5fa945590e696f634d5b76bf8c30e47e69027f2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.25-any-stack-14c24db5.tgz"
    version = "0.0.25"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "7f0ace9b9f702b000a76f560618490fe0bca98da6bc4bb61224599d686953d20"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.133.tar.gz"
    source_sha256 = "7ac5f3d43c070dafc3f973f69a2a3bb850b4bbb022cf7aaf2b2864fb79291188"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.133-any-stack-7f0ace9b.tgz"
    version = "0.0.133"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.133"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.25"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.107"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.99"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.55"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.99"
