api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a8d2193acfa5d59707e348437ba0974312dcf5ec2ca675f30780cfd2b0dfcf5d"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "0b5aee17e388fed32ce934d93d9113773f59189326c27d668c5e78a1947f0f27"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.59-any-stack-a8d2193a.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a458b824886cc530c7f4ca1d172eaf946a79052f15b92c10e0d0fd113cda80e0"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "40db1d3cd3e5865fdf04ac4b92deab4f621cd7cdd892374d2b65b57f4c89d071"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.67-any-stack-a458b824.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "a458b824886cc530c7f4ca1d172eaf946a79052f15b92c10e0d0fd113cda80e0"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "40db1d3cd3e5865fdf04ac4b92deab4f621cd7cdd892374d2b65b57f4c89d071"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.67-any-stack-a458b824.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d6907b288191140b499cacc9f8d0b67b2021bbbd6f9f63b93a447bfae0da01c1"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.24.tar.gz"
    source_sha256 = "41d094fa56fa554d31937a9858f66a91b224a79d157e035caebbaaefccb0b576"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.24-any-stack-d6907b28.tgz"
    version = "0.0.24"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d12ce42cd3d2cdedef320db764004a493ff1d87c3e87cda2098d7eb36f96aea4"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.32.tar.gz"
    source_sha256 = "c4f3c0ebbc4dee5a155cc8129c302bdcf802c67d893d5a4a0e8e82d8ea2255bc"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.32-any-stack-d12ce42c.tgz"
    version = "0.0.32"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "d12ce42cd3d2cdedef320db764004a493ff1d87c3e87cda2098d7eb36f96aea4"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.32.tar.gz"
    source_sha256 = "c4f3c0ebbc4dee5a155cc8129c302bdcf802c67d893d5a4a0e8e82d8ea2255bc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.32-any-stack-d12ce42c.tgz"
    version = "0.0.32"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "14ab1823e9baba1a4c2ca1e137fe5b2a262efe1448a67884b1c4cf42901e329e"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "4889ff2c347efcdd5c5d4f1da84569f2e8fa17eb207681f72c47907613329606"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.64-any-stack-14ab1823.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "cc63f140ac1ed90ccd9c006a3a577e39e8dedcbeec42171e28048e7fe768946c"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "a6a7b27c16540f5c1624974e4d6784c986fd007eaaf1112c151d64d3afaf1345"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.74-any-stack-cc63f140.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "cc63f140ac1ed90ccd9c006a3a577e39e8dedcbeec42171e28048e7fe768946c"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.74.tar.gz"
    source_sha256 = "a6a7b27c16540f5c1624974e4d6784c986fd007eaaf1112c151d64d3afaf1345"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.74-any-stack-cc63f140.tgz"
    version = "0.0.74"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "09cbe1de1f7ece28b0f0f3b6bb01672386c8589781f430bf1edfae7515709cdf"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "e7d2073c5a0b33fbceb73d66b17210f9cbce8af0460f0af78c91967c2c5d1597"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.72-any-stack-09cbe1de.tgz"
    version = "0.0.72"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8d45686afe4867d7f2d490fc937a85f515f00ec6ffff4d74f7b27323571b49d4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "0ecef56c36ce82bf07ca60ef7ede934ab5ca8c0895dbaf1eba9c78769850bd8f"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.78-any-stack-8d45686a.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "8d45686afe4867d7f2d490fc937a85f515f00ec6ffff4d74f7b27323571b49d4"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.78.tar.gz"
    source_sha256 = "0ecef56c36ce82bf07ca60ef7ede934ab5ca8c0895dbaf1eba9c78769850bd8f"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.78-any-stack-8d45686a.tgz"
    version = "0.0.78"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "d68abde46d36b024f577718bd93965153161285050e480c169b750194caa6833"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "0c1c9f2ec0bb324fd565b5d7015a5a412214c61c967b9ca057b6a834f93f1f1c"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.62-any-stack-d68abde4.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "048f7b53cc1a78c686e9de6da923a27394bd736dc508d1d33e130c8f6699d2c5"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "db3d00e46defadc7225b53abec4334d51facf7d47a13061c81331f1c73dfcf7a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.68-any-stack-048f7b53.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "048f7b53cc1a78c686e9de6da923a27394bd736dc508d1d33e130c8f6699d2c5"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "db3d00e46defadc7225b53abec4334d51facf7d47a13061c81331f1c73dfcf7a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.68-any-stack-048f7b53.tgz"
    version = "0.0.68"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.78"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.68"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.32"

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.74"
