api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "f124f4bc0aac4be847e0ad276db1dfd6fc9d9111ec848a600a7fdf49296676b1"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.33.tar.gz/archive/.tar.gz"
source_sha256 = "ffc643b1c6e2ae0abd5c94c9d620096950f2926e5edf1c9b15089bace25d8172"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.33-any-stack-f124f4bc.tgz"
version = "0.0.33"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "54b72d3df462e63bc521c4b6cf4080466bd15b2cfee9562d3bf7225e3a9a6d66"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.6.tar.gz/archive/.tar.gz"
source_sha256 = "4371f6e4b13fc97cf1c63f0a2cde801f8659158d20f66cdf0154bd779c93fbda"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.6-any-stack-54b72d3d.tgz"
version = "0.0.6"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "ab78cf008230f491bf652bb1c0812226e486e53fbfe336deaa8c7da020cd102b"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.37.tar.gz/archive/.tar.gz"
source_sha256 = "2c34171e2e2a1fd5c96a60eaa0f96c7c17d8af586163ee2872f4809c251ebc9c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.37-any-stack-ab78cf00.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "f31207467335d81df55624b5509dcb11231d286c8dec810f05d806d4660e3c5f"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.40.tar.gz/archive/.tar.gz"
source_sha256 = "eb6753e27f82fb422e8e81027f6cc00b7c96e236fd91c9cdbbb6343bd819a582"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.40-any-stack-f3120746.tgz"
version = "0.0.40"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "b5772b6abf4b1cec32d282666fc40e592a5c432560935d2707bf90afff4e78aa"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.32.tar.gz/archive/.tar.gz"
source_sha256 = "fc554e067bb102429d30fe8d39f54d3032c7d9b7a038273d23df49434380b8b6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.32-any-stack-b5772b6a.tgz"
version = "0.0.32"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.40"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.33"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.32"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.6"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.37"
