api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "fa189cfa780a460c01e6b765d466d0b9c498688d5e34d20b2993103082f83164"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.9.tar.gz/archive/.tar.gz"
source_sha256 = "d105e37ff12126bdcc8c45ed7dea0aef6cc98660291f5470450e9e2b38cf0a01"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.9-any-stack-fa189cfa.tgz"
version = "0.0.9"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "686690036c3613f567054309bef85aae4d70dd29aa8df11de6a3ea85a3a6d75f"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.20.tar.gz/archive/.tar.gz"
source_sha256 = "4d10bb3296f3802d2fc22bdd6deba5b856f6d375cccb3201d45ca6741c1e7ed2"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.20-any-stack-68669003.tgz"
version = "0.0.20"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "d7eada3779ad1b21a8f86b9b8f565e9cf518f06750bfdd5d1b59d88832ebaff0"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.15.tar.gz/archive/.tar.gz"
source_sha256 = "a095d142d5ee52778b18c3575a27a282d665c2176eb4fef89f84634a4e37cef5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.15-any-stack-d7eada37.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "58065f2eed9a5c6a778a80e1a30256bf3f2b80614946b37d1808027ad2133424"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.7.tar.gz/archive/.tar.gz"
source_sha256 = "a64e2c1a66e2b569c9ad35b9688e2f7e0770c2471bd3cc08bbb3edebf546fb4a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.7-any-stack-58065f2e.tgz"
version = "0.0.7"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.9"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.7"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.20"
