api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "81d46b248cbaf15cbd85f3cc7c04d003a0de0d36dd00ad028dff5f52156ed563"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "f443a01a15bb4a1a79e2924688b93406a5f3258f98f87b5d4a5ad71c40b8f7f8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.115-any-stack-81d46b24.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "4349ccd18bf38a63cc447d47ccb326234afb645cf122d276fbcccbc21c00b07a"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "87b4f9c1d8bfd723b434a05dcb6cc538d542171e964a02403ad8feb419adee97"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.68-any-stack-4349ccd1.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "b4761af6fda5b679405053074fd6da4c579c92399d9e7f8df03a9983213215a5"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.114.tar.gz"
    source_sha256 = "4bf21399c8b7173d723ebc7fbe5dc6f6ce8f910f93594d22895949f568c04906"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.114-any-stack-b4761af6.tgz"
    version = "0.0.114"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "2f6b68893b368f7bd7c6df1b55610112404d0a5b183405d462e1ea9290efc674"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.126.tar.gz"
    source_sha256 = "67c39d0616d770447c1b142bf7e857a7ae34a2987f547851b2ce702930df71d2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.126-any-stack-2f6b6889.tgz"
    version = "0.0.126"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "f3fa233f904d8ac8fd44abe74daf2b13c048a15d6fe74d2b1ab7d278bc850a78"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.120.tar.gz"
    source_sha256 = "eeec0b88d7c5ea01e86edc8e6eacade64c66883cc67e041543dde22dbdc767f2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.120-any-stack-f3fa233f.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "6a71321d1d096ffec72acdc707932b3e3364fbbadea45741513db94bab82be71"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.43.tar.gz"
    source_sha256 = "8a3ab36445d674c108d155262666b1dd9efa084a1dd9b1b98a8c3898a0e531f6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.43-any-stack-6a71321d.tgz"
    version = "0.0.43"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f53300cd8b742bb08235a9f8ad4cd23aa7738cf4dc50be5810d9a49177782b1a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.155.tar.gz"
    source_sha256 = "38870fec85e70e7e5bfb25a2a4bb89e80678ded3b0e27ee5be332a33dc8a681a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.155-any-stack-f53300cd.tgz"
    version = "0.0.155"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.155"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.43"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.126"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.115"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.120"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.68"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.114"
