api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "ef7b5f5c08a218065e5446028070ea96158acfe2738f22508388328a13af416a"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "cf886a80bd9d015f8d3459daedc3d940722751e570f69e49d9f48afa4a8479a9"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.51-any-stack-ef7b5f5c.tgz"
version = "0.0.51"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "f64da026b66e26f667b0947c5ab6ac4bdd270878abd546074457419874ca41ad"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.15.tar.gz"
source_sha256 = "9b9132bcb83af827cf5dca32c6c21cc61951da7fe6c4dceae446171b23cd3518"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.15-any-stack-f64da026.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "649a46b842247bfa0482ffaf5fada3e08ad73e4a7dcbf64970c0157b1cd15c30"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "729c3c7a14535c35b5acecdd531122e29a1ce20ff6905c839f9da8d4c781488d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.55-any-stack-649a46b8.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "efb427d861b6021cd0e3820144d0653b4d82c9da81b288e21941245be18a2f8a"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.64.tar.gz"
source_sha256 = "d858605ff1f82e1f7bb9f60caa875d2861ec0642393c745462fc4a7407bd8cae"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.64-any-stack-efb427d8.tgz"
version = "0.0.64"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "9cc50f8202e32a55929a11f33ddc0f654b6c68d64c120c1a37584ae5f1cfd69d"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "3e4537590a2c5dfd12157ea7471724bbf32a4761b306988ee366fe7ed0962a67"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.52-any-stack-9cc50f82.tgz"
version = "0.0.52"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.64"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.55"
