api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "050fcdc93ab5d30d99e7fb463de1b08de7592c85cf3d623c07cb8470d5bb7204"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.57.tar.gz"
source_sha256 = "f9f99b11d284980aba3415515e9f77ec385f9e0e2e36f11fb589305b3dc44595"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.57-any-stack-050fcdc9.tgz"
version = "0.0.57"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "21e0b70847f91b81869cd28066fec9e0cbdba15fd3b4635a96bc50c8629a240d"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.22.tar.gz"
source_sha256 = "63db76ed6add97350623bbbcb664e262c444dd8eb934d724a30a2ac84045fa66"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.22-any-stack-21e0b708.tgz"
version = "0.0.22"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "47eb18822201801cf8b4b2e6f8aed4442bf988231f1573b62452ccbc9681019a"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.60.tar.gz"
source_sha256 = "cad68b3d6d58affc2591fda4a6438d393af5104df702e7c01650f6fc22c22400"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.60-any-stack-47eb1882.tgz"
version = "0.0.60"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "78e6993097f706831adc887f6d56e3ec005f515c3ddac31fb3a675745280d095"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.69.tar.gz"
source_sha256 = "e739386996d86255549a764e01b1fc5d5e73b9983bbf3fb3788d1b151ce7c2a5"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.69-any-stack-78e69930.tgz"
version = "0.0.69"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "3309b6b217e1fa470ab7f8db45402fcfffdfbfd9acf218e30c952abf5c926e43"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.59.tar.gz"
source_sha256 = "affcff1c8f06e5b2cb26da6e75be761b7ae4e3d4e9afe29a09073e51fadd699a"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.59-any-stack-3309b6b2.tgz"
version = "0.0.59"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.69"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.57"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.59"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.22"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.60"
