api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "02a569edb89b8f485334c0fa402b31fc7c975592678be7507aa089de10119f66"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "31f3357df08e1b24c148bf52451c4dffbe6adb31d2cce61f7d077d5940cd0a7b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.52-any-stack-02a569ed.tgz"
version = "0.0.52"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "af13b2cc7755ecf9f0298793d1acb6f21b36c19b26c17eebe1e4f3187ab0cc30"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.17.tar.gz"
source_sha256 = "4b80bbc0bf8ddb562f802f642b14c75ea8472151e8b935b12526574a14bac83a"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.17-any-stack-af13b2cc.tgz"
version = "0.0.17"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "28348195643aae56e7fc32d17d7a8e248e0742414242ac809fcec91d9b1d1cc9"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.56.tar.gz"
source_sha256 = "273c850ea604c13332dd1356cbfe2f96de515f7964f711fc7067991c7e82f4d9"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.56-any-stack-28348195.tgz"
version = "0.0.56"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "e18fd373d0cd6e046e69862485c577a0eb7b58d59db69d46d6070d745f116657"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.65.tar.gz"
source_sha256 = "6895e3329d9cb996e5c10d65a47ecff93882b496d63818b7f582b9fee55c696d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.65-any-stack-e18fd373.tgz"
version = "0.0.65"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "d40097cd75e3918e33129df36b8381a6f1499c4fb265d5dba937d79c12e11c7c"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.54.tar.gz"
source_sha256 = "ff393e25fb7a4728041f48086f5b66dc430e227364a5697cf9575d74792c0df1"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.54-any-stack-d40097cd.tgz"
version = "0.0.54"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.65"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.54"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.17"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.56"
