api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "02a569edb89b8f485334c0fa402b31fc7c975592678be7507aa089de10119f66"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "31f3357df08e1b24c148bf52451c4dffbe6adb31d2cce61f7d077d5940cd0a7b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.52-any-stack-02a569ed.tgz"
version = "0.0.52"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "f64da026b66e26f667b0947c5ab6ac4bdd270878abd546074457419874ca41ad"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.15.tar.gz"
source_sha256 = "9b9132bcb83af827cf5dca32c6c21cc61951da7fe6c4dceae446171b23cd3518"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.15-any-stack-f64da026.tgz"
version = "0.0.15"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "649a46b842247bfa0482ffaf5fada3e08ad73e4a7dcbf64970c0157b1cd15c30"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.55.tar.gz"
source_sha256 = "729c3c7a14535c35b5acecdd531122e29a1ce20ff6905c839f9da8d4c781488d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.55-any-stack-649a46b8.tgz"
version = "0.0.55"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "e18fd373d0cd6e046e69862485c577a0eb7b58d59db69d46d6070d745f116657"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.65.tar.gz"
source_sha256 = "6895e3329d9cb996e5c10d65a47ecff93882b496d63818b7f582b9fee55c696d"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.65-any-stack-e18fd373.tgz"
version = "0.0.65"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "c734d63938bc11677096c441f28e5dd6f2863078177a78f6ba41c35848a501aa"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.53.tar.gz"
source_sha256 = "57594669cb4bc7f0ea1ae617cde222da9953fa53743043f1e2bce740b112ea71"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.53-any-stack-c734d639.tgz"
version = "0.0.53"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.65"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.53"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.15"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.55"
