api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core"
name = ".NET Core Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-aspnet"
sha256 = "e241d2fe66e1b731a796ecb2e21746fe4d9c08bb35b840969c48a177eb0044f9"
source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.49.tar.gz"
source_sha256 = "c5ac3b1ed2253bebd4dad4f93e5f383037750ab9c91e0a5a0c1e2c67c6fc7b6f"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.49-any-stack-e241d2fe.tgz"
version = "0.0.49"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-build"
sha256 = "419b67306f2d19a71ccfda0b63309f9551bf092f337180a609fecb12079a934e"
source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.14.tar.gz"
source_sha256 = "46cc4fbd0fdfd5587879c175c372fb3c58e9e08f2360fa03c0a25d1ad2d6d9a8"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.14-any-stack-419b6730.tgz"
version = "0.0.14"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-conf"
sha256 = "ce36dbf8e4bca08441b8b412cff087fb52a5b1d3a642273f7f24404ae0004e7c"
source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "015a9297331f999ee5628394b6e69089c237d34d5d584610e6edeed7bb3c77d7"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.52-any-stack-ce36dbf8.tgz"
version = "0.0.52"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-runtime"
sha256 = "53726f2dac478d5442bed6aa64eb80d3b292d04a018d347f4ce47d922332f9a5"
source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.60.tar.gz"
source_sha256 = "4002565381e93ce2fe1f905e47adb8aee284b6087b05c7b5996709c63044963c"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.60-any-stack-53726f2d.tgz"
version = "0.0.60"

[[metadata.dependencies]]
id = "org.cloudfoundry.dotnet-core-sdk"
sha256 = "aaceaadf93abbb84c616d0e3370f4db1c359355fcdd0bbaffbb85ece5af775f4"
source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "859de8ee123a910158d8affacb9f8fa7cec6d2d69810a52e85acb7b2eb2a339b"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.51-any-stack-aaceaadf.tgz"
version = "0.0.51"

[[order]]

[[order.group]]
id = "org.cloudfoundry.dotnet-core-runtime"
optional = true
version = "0.0.60"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-aspnet"
optional = true
version = "0.0.49"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-sdk"
optional = true
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-build"
optional = true
version = "0.0.14"

[[order.group]]
id = "org.cloudfoundry.dotnet-core-conf"
version = "0.0.52"
