api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "f15c0bd82a93492c964d20a0d7ca7245ee1244cd798c82ce91e7d4c4356764d9"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.113.tar.gz"
    source_sha256 = "57887bf19fab07458cf3b0668a17d04672f574f358fda2050f83794691ae1a63"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.113-any-stack-f15c0bd8.tgz"
    version = "0.0.113"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "7b871ab13c13a9e9f00ecaf4862ddbd0adca25ba0e89c4652abc11bd966aafaf"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "343465e4d4204a9a48f1822c38e27cade7668a8b7621c186febe7b9df19c03ab"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.65-any-stack-7b871ab1.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "4c4c151ae6f3d385a9372acad2777ae0d200ea907ae105c7980d4c7cd77da0af"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.112.tar.gz"
    source_sha256 = "6b663ee0982b68280d9098a77ef206ee8b4699a44cdc89e6c6821a9f11728f37"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.112-any-stack-4c4c151a.tgz"
    version = "0.0.112"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "b60220cfb142625050e79600bb293cf9b55a74c9e4530256a23afe2cb3c70ff7"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.124.tar.gz"
    source_sha256 = "9a8793b79ee42db8a7ed59f30f8545b7d261429f3743e140f50e0e28b87033af"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.124-any-stack-b60220cf.tgz"
    version = "0.0.124"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "496f5767f89541b1d7013abbd4eeb7ba8f8d29d2656c761fd05d78691b0ec514"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.119.tar.gz"
    source_sha256 = "a2e104538235312cb9b417b5f5c26cfe96f63d5c95bd7d16e7f257bb867e2863"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.119-any-stack-496f5767.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "b11787055bb5112210bfed5f3a0a27a5cfcbf8b36c8a38da16e90e05c8c4c560"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.40.tar.gz"
    source_sha256 = "afa517fe4614c2c4e6fafd081d22da04476ddadef71b59477131436b538735b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.40-any-stack-b1178705.tgz"
    version = "0.0.40"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "85e93f4e818ddb0dfc6e4bcf5130291dd6b74c9c4394fc124dda1e9e9851f79f"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.153.tar.gz"
    source_sha256 = "1907503b7d82aff117f9d6fd5f1c42e531337b157093a5525519df1af9f5a5ae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.153-any-stack-85e93f4e.tgz"
    version = "0.0.153"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.153"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.40"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.124"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.113"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.119"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.65"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.112"
