api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "0a95f5b05c291c646b80900d9cc343952efef485448fd589cd46b24a7d58d52b"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.119.tar.gz"
    source_sha256 = "557cf0d906c1ef3034c4d7e426a5aae98b4d0d519290770c2b2af52abe47b7c5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.119-any-stack-0a95f5b0.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "4349ccd18bf38a63cc447d47ccb326234afb645cf122d276fbcccbc21c00b07a"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "87b4f9c1d8bfd723b434a05dcb6cc538d542171e964a02403ad8feb419adee97"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.68-any-stack-4349ccd1.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "2a6d1c199d41d487157cfd6275f9c31189e56b908f5a8af2d604cb0a71b6227a"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.115.tar.gz"
    source_sha256 = "f60fecdd90630ac3a009756a77d885da0fc9ac0095424a1a0465d123a9a8736e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.115-any-stack-2a6d1c19.tgz"
    version = "0.0.115"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "ba62bf74bc94dc98d9dead211e474759dbd791c377519daeae0843f0f559ae76"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.128.tar.gz"
    source_sha256 = "ecb923bed3d904d7b836de092162886401dad9e086c1596f66269c6cbe6aad8a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.128-any-stack-ba62bf74.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "17fe96794b2d022ad0e19e71460890c9118c16b61fbb0389267d11895af74ac3"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.123.tar.gz"
    source_sha256 = "926850c542b1f608f2c75c9fdb726b04c910db8f88debe3206040092cba83c58"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.123-any-stack-17fe9679.tgz"
    version = "0.0.123"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "e238d06295a0ff9a4d0028840a199eaca4df127e1f1fbc19f055fffc6a00a642"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.44.tar.gz"
    source_sha256 = "405c5f09708e846c1b0e14ecbdad7ead852b9289a72c1d44b8bbb4c46e9a9f3b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.44-any-stack-e238d062.tgz"
    version = "0.0.44"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "ad04708fc5b602a2c04f6f170195917a0ffe82fe3a5cd8b246f94f9301598037"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.163.tar.gz"
    source_sha256 = "65f38bcf8a95a641c88429917b174d649869d4ab8a6b35370ea6176e879e46f5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.163-any-stack-ad04708f.tgz"
    version = "0.0.163"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.163"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.44"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.128"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.119"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.123"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.68"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.115"
