api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "7d0173934ffebcf03fcd5bbe016e62e3b17d8c6a78467e75e9082d7746799d36"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.126.tar.gz"
    source_sha256 = "d1ec2dc47a563e4bf80c078a1748af9862ee33b2687062e25e99cab1bd55d568"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet_0.0.126_linux_noarch_any-stack_7d017393.tgz"
    version = "0.0.126"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "4349ccd18bf38a63cc447d47ccb326234afb645cf122d276fbcccbc21c00b07a"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "87b4f9c1d8bfd723b434a05dcb6cc538d542171e964a02403ad8feb419adee97"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.68-any-stack-4349ccd1.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "0ec017ae0096fedd637605e3b637c4c9492872e9e8928fa7f4d782239e044872"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.120.tar.gz"
    source_sha256 = "7a487b95a586914001e19c548f5992b214f8014eb1a0bf239c5abe930be5c18d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf_0.0.120_linux_noarch_any-stack_0ec017ae.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "495a474d37bc44a23a2e642bb8fb5f0baef56c735a08356beec1475fba123c0c"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.133.tar.gz"
    source_sha256 = "e5161146f310e46d1e37baaefbc47a4b1139e0e139f5704ed3534f8ec3116d79"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime_0.0.133_linux_noarch_any-stack_495a474d.tgz"
    version = "0.0.133"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "64abe7c38e220c6513a687a2ff983d540ff0d62153a357edb3dcdd2da9afdf56"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.129.tar.gz"
    source_sha256 = "124c65468efa517b8ff004e545973c97120ee3ffde12d3747a88181d6059ceae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk_0.0.129_linux_noarch_any-stack_64abe7c3.tgz"
    version = "0.0.129"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "2737099d0dc09df07edb5e0988d04d02dcb45b95d20d7671bc482ef0d197975a"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.49.tar.gz"
    source_sha256 = "4b80c52f33873054735b6ae18287c39f32b361d89106ea9ef9e185ca53cc2983"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu_0.0.49_linux_noarch_any-stack_2737099d.tgz"
    version = "0.0.49"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "ea27057d92b619a098ae655e95081629f7900eb9a8a0910d673aaa17c60fb366"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.174.tar.gz"
    source_sha256 = "3858f356dbac9cd348bfab74fb4017fc64192108828b47ad761624369d941bc6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.174_linux_noarch_any-stack_ea27057d.tgz"
    version = "0.0.174"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.174"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.49"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.133"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.126"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.129"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.68"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.120"
