api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "aaf1da5b995b73262eaca1abfc15ccf8e37fdb589858dcc782b412e896016c0a"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "be3fc2e4f82cfc98ceacf19b384ca1fd88c4d06dc260b47233a3f042f32179f8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.107-any-stack-aaf1da5b.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "44819580bdb583e01f02aeb6964df5caad4f91acaf8da6ccf195b305db508553"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "30530eeafe1349b32b0860fdc18c4bc7fd51f5150fc62f8c9265f3801aec13e5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.61-any-stack-44819580.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "1d14d687ca597ae76caf5811dcea0a33f87d5432e3d0dabc76db793dd79c0524"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "b78f9ce91f375d38a59c3ebadd974c6932cbae7227c93835a8257f66c46c1155"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.106-any-stack-1d14d687.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "ec1f18073a1fb7c45745ae52a5393bdb24713c5fb1be822ceec326c2c4b682b3"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.118.tar.gz"
    source_sha256 = "c4d552c3b1879a5632b54037e51996f3a0852692b31bae7066b73a8b0dae9753"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.118-any-stack-ec1f1807.tgz"
    version = "0.0.118"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "ad4e4e25376b88b1953299055ed74c8f906b162d3cb4978e411ec8ca36a876dd"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.113.tar.gz"
    source_sha256 = "7050fc5ab49e15f811ca44c9df390d68fbd058a8da0fd97768e1cd60357078d2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.113-any-stack-ad4e4e25.tgz"
    version = "0.0.113"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "bcd2afca07429170e1f2227c5262a0af5efe01dd42b8fe44d3c393cb3114eeaa"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.35.tar.gz"
    source_sha256 = "54ef1a7cccb9099d033959ac0796f5fe44a75796620ab8c2e1a46695faef4da4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.35-any-stack-bcd2afca.tgz"
    version = "0.0.35"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.35"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.118"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.107"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.113"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.61"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.106"
