api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "f93b5eeda3f4d9fd77816b7525cfe1975939399264dbe92ce33aef2f8066d969"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "538f2885b44163f06bb34260e3390fbce774f14339f08f53923c5939cdc90f8b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.108-any-stack-f93b5eed.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "44819580bdb583e01f02aeb6964df5caad4f91acaf8da6ccf195b305db508553"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.61.tar.gz"
    source_sha256 = "30530eeafe1349b32b0860fdc18c4bc7fd51f5150fc62f8c9265f3801aec13e5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.61-any-stack-44819580.tgz"
    version = "0.0.61"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "ff3a4019c91947b8ee85d5da457d4c43d60a511d536fcedaf7570acbe4a63494"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "08c3f68b3c38e04731e5ecf364fce002a96e88cd46e1f073a2f32d5879721241"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.107-any-stack-ff3a4019.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "23991e7c09a34b7ac0c10ea4042e736f1ce7a945ff637461dffecbaba6daf3db"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.119.tar.gz"
    source_sha256 = "9e7d655f6d8aed88a3a0bb2ad79f39d356b7cbcbffedb494e1c7d90dd8caa403"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.119-any-stack-23991e7c.tgz"
    version = "0.0.119"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "94f5db6ec1521ec4b45e5bcc7cff53b9951f3edcad61f8dd6c18c8af026d1c30"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.114.tar.gz"
    source_sha256 = "1fbaf1b4c2c046a57f1359943fc310b2a6659aeb012569f8c99d4f6242975256"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.114-any-stack-94f5db6e.tgz"
    version = "0.0.114"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "fec2f155fb70f7a5116f43729d88d577772689706c84391ed9001735f5c7994c"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "c3e383151488397f212669a1278f987fa0c36a6be36f6049004f0c0b68983948"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.37-any-stack-fec2f155.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.37"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.119"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.108"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.114"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.61"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.107"
