api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "006a29866fe71693fd34a6b148725412fe5b40d3b4b45ab91647a824f111019b"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.128.tar.gz"
    source_sha256 = "3053cea12023272263f713e731000e07c5acc3b47b12b3207c2b52b09ae991f9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet_0.0.128_linux_noarch_any-stack_006a2986.tgz"
    version = "0.0.128"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "2ef58689098300fdbf56e10052b5c8df942b0e1298187ffea03f7275939ebe6d"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "c79670babae5594b2eff8cbe7ced4c62a849a07ea8b5997399760a990dbe24b2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build_0.0.70_linux_noarch_any-stack_2ef58689.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "f5e770da43aa4d015a1efbaad3fde6e002e2ea56c09990bf7ea4bae12b39fe60"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.121.tar.gz"
    source_sha256 = "fd6b141a03315e1257176a3066cd5817203b15eb37dc6849d459049791b25338"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf_0.0.121_linux_noarch_any-stack_f5e770da.tgz"
    version = "0.0.121"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "fa9c2b6632c95d73f4edeee04d9af21fd6dda8df42ccbe1a82b6c0a660337621"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.134.tar.gz"
    source_sha256 = "3d95c7f69603720a6d855a51109a11063294a7d40a46b62007c2a0c1048ff0bc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime_0.0.134_linux_noarch_any-stack_fa9c2b66.tgz"
    version = "0.0.134"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "88f57001cefa854087315934ddd4e9e85c267d34797df0a5de320344c90f108d"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.132.tar.gz"
    source_sha256 = "f9cc1c1f2cbd826a90992876607c04d74cf1bfa9a75009848780f9d24f182fe0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk_0.0.132_linux_noarch_any-stack_88f57001.tgz"
    version = "0.0.132"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "8362a7254ce3ead513935dd2732db5a55f770df9e36ce95136accf047ed4e938"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "4261315fb9849df01bace33869e75c13fc1deda89894e25bd839c73720039645"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu_0.0.51_linux_noarch_any-stack_8362a725.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "ae92b009fb167ed56cf19e5050480606ca7e17dda977e73225f4d1e43d03956e"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.178.tar.gz"
    source_sha256 = "9b6f8dd2f03d5ee704605bbca4503d973d08a7ed236712c66de5c7a71867af46"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine_0.0.178_linux_noarch_any-stack_ae92b009.tgz"
    version = "0.0.178"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.178"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.134"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.128"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.132"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.70"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.121"
