api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "1899534654f48ac86f336929266975896c06a1ce9febdd1cfe9818662b369e81"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "5652f71c37884c77d8c025f77fac0b0427cb4cd17643b5c0fd83cb369a038b99"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.104-any-stack-18995346.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "9a7b6a1b165736fae3676346e96e443570467bf3c7a40d2191e61abd96d16780"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.43.tar.gz"
    source_sha256 = "d0f2ba5f9e6e05c4115ed6b4fa87ed323b88477d932bbdfc8f9a36de8da51ce7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.43-any-stack-9a7b6a1b.tgz"
    version = "0.0.43"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "f0ca71a290724fd968d72cf71db9261a5c54d695a00b3eb73efebbbc566d3ba4"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.86.tar.gz"
    source_sha256 = "9b2c5ff871ceef8bfa4535babee44f470aa66463af994210bd1781f920b90645"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.86-any-stack-f0ca71a2.tgz"
    version = "0.0.86"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "b53e59f1477b3acff5d2a824747980574707b9c8bf195219c1d823e85d4d88ab"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.94.tar.gz"
    source_sha256 = "459818a93b72b6c36c1ca36c4058eae26d46996ec2db2c8e87784ca1518cfda6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.94-any-stack-b53e59f1.tgz"
    version = "0.0.94"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "bb38c2e99d6f0ac47866c8d5c65e5acc65a8ece209175e285e4f528570281aec"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "f925e50a2977e77cd4a78c74a135559b072d41e45d327558904b6db94c09c0b7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.87-any-stack-bb38c2e9.tgz"
    version = "0.0.87"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "0ae2f426be6bc185e0aedff22643eac763aa2f5b970897d3d40a11b1a40e3cc7"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.11.tar.gz"
    source_sha256 = "da7b6c6d9fbbb4489d6abf51febe466a1347012524db0503bb564cd26003b2b6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.11-any-stack-0ae2f426.tgz"
    version = "0.0.11"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "f4398686d3b9d254dfc695faea37761a6a7abb8ca12ffaad1e4a0ccd6a76009b"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.146.tar.gz"
    source_sha256 = "1baa50682f2fe092a9f748997ef1221f3a327066725348ef81cb9e0cd44c4e79"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.146-any-stack-f4398686.tgz"
    version = "0.0.146"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.146"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.11"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.94"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.104"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.87"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.43"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.86"
