api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "0368b6ea6b3fe1603c04a7df6dbf13bd445af8f04b484d67a0144b7132d9ebd1"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.109.tar.gz"
    source_sha256 = "98b34959fecc9a8f7363810afeb2a1db1953e8572f4cd769b833c583a36e6fef"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.109-any-stack-0368b6ea.tgz"
    version = "0.0.109"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "1cc129be7017afff8077e2d929251133e315dd924a57a89fd2e8d46878e65b6e"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "6ae05c431538e3373a444d0da0e9ad0b77be97f1755ca7fd7bce892bfb9c42fb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.62-any-stack-1cc129be.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "ffd3fe7de7d090d22049f2a82b23d62497a0f3a14044f070dec5d73ac08f6071"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "9375fefcc06ec0afe884c48bf35ce99f57c47c36e96aad9530cd5ae86b129075"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.108-any-stack-ffd3fe7d.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "f4e4a84daf0847bc5ab37b85418acdee2814001bef2c6921487518100dc43978"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.120.tar.gz"
    source_sha256 = "b2dd2eebb251bd36340ebe96ff0a7da7db9a4e8ecfcf40c6e68e411c7c8cf718"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.120-any-stack-f4e4a84d.tgz"
    version = "0.0.120"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "94f5db6ec1521ec4b45e5bcc7cff53b9951f3edcad61f8dd6c18c8af026d1c30"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.114.tar.gz"
    source_sha256 = "1fbaf1b4c2c046a57f1359943fc310b2a6659aeb012569f8c99d4f6242975256"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.114-any-stack-94f5db6e.tgz"
    version = "0.0.114"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "9dbc40feaf444ecd179922c10d02a9672fef94a4974df164a322ace4083d2c74"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.38.tar.gz"
    source_sha256 = "2dfc6ce29fdbc714328bf367e8bd7cfae4ed0b1ff623d00ff363f064f5eeaf0d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.38-any-stack-9dbc40fe.tgz"
    version = "0.0.38"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.38"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.120"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.109"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.114"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.62"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.108"
