api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core"
  name = ".NET Core Buildpack"
  version = "{{.Version}}"

[metadata]
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/archive/v0.5.0.tar.gz"
    source_sha256 = "96c50622096b252b596a33731785ae959992078eada660ae068d86607faee6a6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs2", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    sha256 = "e0ee6a511bc7c1f19640e4c6368673522d8516a5a39d4d99ce44e252a8bae886"
    source = "https://github.com/cloudfoundry/dotnet-core-aspnet-cnb/archive/v0.0.105.tar.gz"
    source_sha256 = "58b7de88f682435fa80df74539d6d5c7a9bd767b2ebcc2f5cde5751337bf5a76"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-aspnet/org.cloudfoundry.dotnet-core-aspnet-0.0.105-any-stack-e0ee6a51.tgz"
    version = "0.0.105"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-build"
    sha256 = "6fa0f71e39489e9cd857903f6b32f41c0f30c68d50a3d6fbb3adaeb2b552d98f"
    source = "https://github.com/cloudfoundry/dotnet-core-build-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "832b310cfc985fb4b69f34f1b051fddc23044c9d19b46b6cb9a069e67793cdfe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-build/org.cloudfoundry.dotnet-core-build-0.0.60-any-stack-6fa0f71e.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-conf"
    sha256 = "1d14d687ca597ae76caf5811dcea0a33f87d5432e3d0dabc76db793dd79c0524"
    source = "https://github.com/cloudfoundry/dotnet-core-conf-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "b78f9ce91f375d38a59c3ebadd974c6932cbae7227c93835a8257f66c46c1155"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-conf/org.cloudfoundry.dotnet-core-conf-0.0.106-any-stack-1d14d687.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    sha256 = "a405f7e3129ab2032e73856305e2bf270008612a812e9117010c7737f2b5fc2c"
    source = "https://github.com/cloudfoundry/dotnet-core-runtime-cnb/archive/v0.0.117.tar.gz"
    source_sha256 = "a44b5d6dcdfd8fe7c16393b77ceef1a62a50f568e572a9764be56f237a361ec5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-runtime/org.cloudfoundry.dotnet-core-runtime-0.0.117-any-stack-a405f7e3.tgz"
    version = "0.0.117"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    sha256 = "c4f2ae59b4013b65543c6e62f834829f2f99aa207a58ba82bfedecd9204f4d30"
    source = "https://github.com/cloudfoundry/dotnet-core-sdk-cnb/archive/v0.0.111.tar.gz"
    source_sha256 = "7817f0d914a007a0775ab7fb985abcc76f0ff92e6b612c0f7b5b96586e564aac"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.dotnet-core-sdk/org.cloudfoundry.dotnet-core-sdk-0.0.111-any-stack-c4f2ae59.tgz"
    version = "0.0.111"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.icu"
    sha256 = "e31a6377cedc1c75facec7d0117294644ddd0c69d1b75c17a80248895e3e98f8"
    source = "https://github.com/cloudfoundry/icu-cnb/archive/v0.0.34.tar.gz"
    source_sha256 = "b67f5d40dbf41a63f30eb9885be9e1e19dd06ea8420b0ee044d8343ce9ccd636"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.icu/org.cloudfoundry.icu-0.0.34-any-stack-e31a6377.tgz"
    version = "0.0.34"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.node-engine"
    sha256 = "36758a0b2ff52326bacbed1c5070c93321094f995bab5d020cf469d0c4c6969a"
    source = "https://github.com/cloudfoundry/node-engine-cnb/archive/v0.0.150.tar.gz"
    source_sha256 = "6631db4ae1eeeb073b334a01a71f8edb435bef8426fe19e96b0c5d7d42609658"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.node-engine/org.cloudfoundry.node-engine-0.0.150-any-stack-36758a0b.tgz"
    version = "0.0.150"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.node-engine"
    version = "0.0.150"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.icu"
    version = "0.0.34"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-runtime"
    version = "0.0.117"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-aspnet"
    version = "0.0.105"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-sdk"
    version = "0.0.111"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-build"
    version = "0.0.60"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.dotnet-core-conf"
    version = "0.0.106"
